### ISSUE TITLE
Error on Camo

### ISSUE THREAD

**Issue by Edrard** [mikeoverbay/TankExporter#1]
Good Day

On Getting Camo Textures have next error

Подробная информация об использовании оперативной 
(JIT) отладки вместо данного диалогового 
окна содержится в конце этого сообщения.

************** Текст исключения **************
System.IndexOutOfRangeException: Индекс находился вне границ массива.
   в Tank_Exporter.frmMain.build_customization_tables(Int32 id, String filename)
   в Tank_Exporter.frmMain.load_customization_files()
   в Tank_Exporter.frmMain.frmMain_Load(Object sender, EventArgs e)
   в System.EventHandler.Invoke(Object sender, EventArgs e)
   в System.Windows.Forms.Form.OnLoad(EventArgs e)
   в System.Windows.Forms.Form.OnCreateControl()
   в System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   в System.Windows.Forms.Control.CreateControl()
   в System.Windows.Forms.Control.WmShowWindow(Message& m)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   в System.Windows.Forms.Form.WmShowWindow(Message& m)
   в System.Windows.Forms.Form.WndProc(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Загруженные сборки **************
mscorlib
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
!_Tank Exporter
    Версия сборки: 1.0.0.27
    Версия Win32: 1.0.0.27
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/!_Tank%20Exporter.exe
----------------------------------------
Microsoft.VisualBasic
    Версия сборки: 10.0.0.0
    Версия Win32: 14.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Remoting
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
SlimDX
    Версия сборки: 2.0.13.43
    Версия Win32: 
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/SlimDX.DLL
----------------------------------------
Ionic.Zip
    Версия сборки: 1.9.1.8
    Версия Win32: 1.9.1.8
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/Ionic.Zip.DLL
----------------------------------------
System.Data
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Tao.DevIl
    Версия сборки: 1.6.8.3
    Версия Win32: 1.6.8.3
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/Tao.DevIl.DLL
----------------------------------------
Tao.OpenGl
    Версия сборки: 2.1.0.12
    Версия Win32: 2.1.0.12
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/Tao.OpenGl.DLL
----------------------------------------
Tao.Platform.Windows
    Версия сборки: 1.0.0.5
    Версия Win32: 1.0.0.5
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/Tao.Platform.Windows.DLL
----------------------------------------
Tao.FreeGlut
    Версия сборки: 2.4.0.2
    Версия Win32: 2.4.0.2
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/Tao.FreeGlut.DLL
----------------------------------------
mscorlib.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Xml.Linq
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Numerics
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Windows.Forms.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** Оперативная отладка (JIT) **************
Для подключения оперативной (JIT) отладки файл .config данного
приложения или компьютера (machine.config) должен иметь
значение jitDebugging, установленное в секции system.windows.forms.
Приложение также должно быть скомпилировано с включенной
отладкой.

Например:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

При включенной отладке JIT любое необрабатываемое исключение
пересылается отладчику JIT, зарегистрированному на данном компьютере,
вместо того чтобы обрабатываться данным диалоговым окном.

**Comment by mikeoverbay** [comment]
I can not read russian but..
Does the program load and run?
Does it crash when you apply a camouflage or before the program is running ok?

**Comment by Edrard** [comment]
Hey there m8, its crash. If u give me you mail, I will send you client, so you test it, becouse its Supertest Client(with Italy tanks)

**Comment by Funky7Monkey** [comment]
Same error in English, on WoT version wot_1.0.0.820_na. It is crashing on startup, when it is loading game files. Appears to me to be a problem with the tanknames.txt file:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Tank_Exporter.frmMain.build_customization_tables(Int32 id, String filename)
   at Tank_Exporter.frmMain.load_customization_files()
   at Tank_Exporter.frmMain.frmMain_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
!_Tank Exporter
    Assembly Version: 1.0.0.27
    Win32 Version: 1.0.0.27
    CodeBase: file:///E:/Tank%20Exporter/!_Tank%20Exporter.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
SlimDX
    Assembly Version: 2.0.13.43
    Win32 Version: 
    CodeBase: file:///E:/Tank%20Exporter/SlimDX.DLL
----------------------------------------
Ionic.Zip
    Assembly Version: 1.9.1.8
    Win32 Version: 1.9.1.8
    CodeBase: file:///E:/Tank%20Exporter/Ionic.Zip.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Tao.DevIl
    Assembly Version: 1.6.8.3
    Win32 Version: 1.6.8.3
    CodeBase: file:///E:/Tank%20Exporter/Tao.DevIl.DLL
----------------------------------------
Tao.OpenGl
    Assembly Version: 2.1.0.12
    Win32 Version: 2.1.0.12
    CodeBase: file:///E:/Tank%20Exporter/Tao.OpenGl.DLL
----------------------------------------
Tao.Platform.Windows
    Assembly Version: 1.0.0.5
    Win32 Version: 1.0.0.5
    CodeBase: file:///E:/Tank%20Exporter/Tao.Platform.Windows.DLL
----------------------------------------
Tao.FreeGlut
    Assembly Version: 2.4.0.2
    Win32 Version: 2.4.0.2
    CodeBase: file:///E:/Tank%20Exporter/Tao.FreeGlut.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Funky7Monkey** [comment]
Looked at the code myself, it is crashing while processing the "scripts/item_defs/vehicles/italy/customization.xml" file at `!_Tank Exporter.exe!Tank_Exporter.frmMain.build_customization_tables(Integer id, String filename) Line 884`

**Comment by mikeoverbay** [comment]
OK.. I updated TE to version 28.. It should work with the 1.0 version of the game.
Give it a try and let me know.

**Comment by Edrard** [comment]
Okey, just tested, and its starting =) Already not bad

But, I cant see any Italy tank on ST and normal client =(

**Comment by Funky7Monkey** [comment]
There are no Italian tanks in the live client, and I think you'll need to play with the tanknames.txt file to get them to appear in the ST client

**Comment by Edrard** [comment]
No m8, we have Progetto M35 mod 46 on Live server, its level 8 premium tank

**Comment by mikeoverbay** [comment]
It doesn't load the Italy tank(s) yet.. 
Ill need to add that once I get everything else working right.
Once again.. MAKE SURE YOU CLEAR OUT THE wot_temp folder before installing the new version.
the path looks something like this: 
C:\Users\Mike\AppData\Local\Temp\wot_temp

**Comment by mikeoverbay** [comment]
tanknames.txt is used ONLY for batch exporting tanks for my other program "Terra". It has no other use in Tank Exporter. Tank Exporter was originally written to export tanks for use with Terra and I expanded it as a tool to mod tanks geometry. Terra is BROKEN as of the release of 1.0 of the game and wont be fixed anytime soon.. there is far to much work to be done.

**Comment by mikeoverbay** [comment]
The Italian Progetto M35 mod 46 is in the package file vehicles_level_08.pkg
I'll need to add code to handle that line.. first lets get the rest of this tested OK?

**Comment by mikeoverbay** [comment]
Yes Funky7Monkey... that was because of the addition of the Italy line. Ill start working on adding that line tomorrow of every thing else is working ok.

**Comment by mikeoverbay** [comment]
Ok... I added the code to handle the Italy tanks... 
Unfortunately, the Progetto_M35 is NOT for sale in NA and I can not find it in the data that I download from them WoT API site.
I hard coded this data and the Pregetto now shows up in the tier 8 tab.

**Comment by Edrard** [comment]
So, its will not work for ST client, where full Italy line was presented, thats sad. Why u using API, what data u getting there?

**Comment by mikeoverbay** [comment]
Edward... what errors are you getting? 
I use the API to get the name of the tanks as they show up in the game.. The only other way to do this is cross reference the tanks ID against found in the tanks xml definition and then look it up in the text MO translation files. its a lot more screwing around then just reading it from the API site.
Also there are some other things I grab from there but I don't remember what exactly.

**Comment by Edrard** [comment]
Just Edrard m8 =)

No, I havent errors, but do not see Italian tanks on Supertest Clients.

Its everything in client right now, u do need API, and you can easy read mo files for real names, but its up too u m8, better to not use API.

**Comment by mikeoverbay** [comment]
I don't know anything about the supertest clients. In NA we have the Common Test server. I looked at the data for it and it has ONE Italy tank. 
Is Tank Exporter running OK for you? I'm confused as to what the issue is.. LOL

**Comment by Edrard** [comment]
Supertes its a closed test, with a new futers or tanks. Right now its a full Italy tree test
Yes, its working fine, but I cant get to new Italy tree
And thats all becouse TE using API and not just reading game client folder. So I am asking, why u using it, and not just scan scripts/item_def/vehicles/ folder, if its only for normal names, then its not need at all most of ppl who using you  app do not it, so I cant get it, why you depend on WG API

**Comment by mikeoverbay** [comment]
I actually have a program that allows editing the mo files.
Its called MO Editor.
This is whats in the NA MO file for Italy:
c.g. 90/50 HE-T COMP B T91
c.p. 90/50 AP-T T33E4
c.p. 90/50 HVAP-T M332 (T67)
Cannone da 90/50 T119E1
Conceptualization of a draft design developed at the request of General Francesco Rossi who believed that only light vehicles weighing up to 35 tons would be effective in a new war. Such an innovative design was not approved; development was discontinued when Italy joined the Standard Tank project.
ID36S 6V CA
Progetto 46
Progetto M35 mod 46
Progetto M35 mod 46
Progetto M35 mod 46
R528
There is ONE tank there but it doesn't show up in the game.
Until the line is officially released, your stuck with that Tank Exporter can find.
Be happy there is even a app that allows changing the tanks geometry.

**Comment by Edrard** [comment]
m8, just do not take it so close, I am only give suggestion =) You program really nice, but I cant use it if it cant read new vehicles what not showing in API.
Like I said before, if u give me a mail, I will send u a link on ST client, so u can look by you own.

**Comment by mikeoverbay** [comment]
And I wasn't upset about anything.. I had an old version of this out a few years back called WoT Model Editor. It was on CURSE. 21,000 downloaded.
Someone posted on the NA forums that tanks shadows are messed up after editing at tanks hull or turret.. I have not confirmed this yet. The tanks I edited had no problems.. I'm waiting to hear back.
