### ISSUE TITLE
Tank Exporter compatible with Mir Tankov?

### ISSUE THREAD

**Issue by AdsGM151** [mikeoverbay/TankExporter#100]
I tried to change the path for the game folder.
C:\Games\Tanki and C:\Games\Tanki\res_mod\1.22.0.0
Tank export to an error message with a red cross, can i just set the direction of the game path?

**Comment by AlexNovan** [comment]
Same for me it loads max to tier 3 lod´s and then just pushes error.

**Comment by mikeoverbay** [comment]
if this is active. reopen it. tanki isn't a normal folder name for world of tanks.
