### ISSUE TITLE
Complex WOTMOD

### ISSUE THREAD

**Issue by QinSparrow** [mikeoverbay/TankExporter#101]
I want to ask "how to load complex wotmod, for example, a re-model wotmod, may contain several dozen of maps, via the resmods"
I find that the resmods path can load standard wot model with its chassis/gun/turret/hull and AM/ANM/AO/GMM texture maps, but when I try on complex wotmods, it failed.

**Comment by mikeoverbay** [comment]
Im sorry.. I can't help without the model that's modded.

**Comment by QinSparrow** [comment]
you are very nice, thank you
