### ISSUE TITLE
System.NullReferenceException when attempting to extract models from WoT version 0.8.11

### ISSUE THREAD

**Issue by lolnothecomplainer** [mikeoverbay/TankExporter#104]
Tested on every install available in the current build (139, 127, BUGs, etc.).
I attempted to use the application to view and extract SD models from an old version of WoT that I had downloaded. To my understanding it's a complete build and aligns 1 to 1 with the actual version from 2014. A problem arose on the initial bootup of TankExporter when World_of_Tanks - 0.8.11/res/packages/ did not contain a shared_content-part1.pkg file like the modern versions do, but a simple rename of the smaller shared_content file worked fine for that.
Shortly after, the app ran into a bigger issue when requesting the res_mods folder. Going into res_mods and selecting 0.8.11 initially loaded part of the content, but then this error arose:

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Tank_Exporter.frmMain.load_tabs()
>    at Tank_Exporter.frmMain.frmMain_Load(Object sender, EventArgs e)
>    at System.EventHandler.Invoke(Object sender, EventArgs e)
>    at System.Windows.Forms.Form.OnLoad(EventArgs e)
>    at System.Windows.Forms.Form.OnCreateControl()
>    at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
>    at System.Windows.Forms.Control.CreateControl()
>    at System.Windows.Forms.Control.WmShowWindow(Message& m)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
>    at System.Windows.Forms.ContainerControl.WndProc(Message& m)
>    at System.Windows.Forms.Form.WmShowWindow(Message& m)
>    at System.Windows.Forms.Form.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
> ----------------------------------------
> !_Tank Exporter
>     Assembly Version: 1.0.0.138
>     Win32 Version: 1.0.0.138
>     CodeBase: file:///F:/WoT%20poking%20around/TankExporter/!_Tank%20Exporter.exe
> ----------------------------------------
> Microsoft.VisualBasic
>     Assembly Version: 10.0.0.0
>     Win32 Version: 14.8.9032.0 built by: NET481REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.9206.0 built by: NET481REL1LAST_B
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.9032.0 built by: NET481REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> System.Configuration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.9032.0 built by: NET481REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Core
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.9200.0 built by: NET481REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> System.Xml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.9032.0 built by: NET481REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> Accessibility
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.9032.0 built by: NET481REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
> ----------------------------------------
> System.Runtime.Remoting
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.9032.0 built by: NET481REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
> ----------------------------------------
> SharpDX.Mathematics
>     Assembly Version: 4.2.0.0
>     Win32 Version: 4.2.0
>     CodeBase: file:///F:/WoT%20poking%20around/TankExporter/SharpDX.Mathematics.DLL
> ----------------------------------------
> Ionic.Zip
>     Assembly Version: 1.9.1.8
>     Win32 Version: 1.9.1.8
>     CodeBase: file:///F:/WoT%20poking%20around/TankExporter/Ionic.Zip.DLL
> ----------------------------------------
> System.Data
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.9191.0 built by: NET481REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
> ----------------------------------------
> FbxSDK
>     Assembly Version: 1.0.4593.24947
>     Win32 Version: 
>     CodeBase: file:///F:/WoT%20poking%20around/TankExporter/FbxSDK.DLL
> ----------------------------------------
> cttools
>     Assembly Version: 1.0.4723.22902
>     Win32 Version: 
>     CodeBase: file:///F:/WoT%20poking%20around/TankExporter/cttools.DLL
> ----------------------------------------
> msvcm90
>     Assembly Version: 9.0.30729.9635
>     Win32 Version: 9.00.30729.9635
>     CodeBase: file:///C:/WINDOWS/WinSxS/x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9635_none_508ff82ebcbafee0/msvcm90.dll
> ----------------------------------------
> Tao.DevIl
>     Assembly Version: 1.6.8.3
>     Win32 Version: 1.6.8.3
>     CodeBase: file:///F:/WoT%20poking%20around/TankExporter/Tao.DevIl.DLL
> ----------------------------------------
> Tao.OpenGl
>     Assembly Version: 2.1.0.12
>     Win32 Version: 2.1.0.12
>     CodeBase: file:///F:/WoT%20poking%20around/TankExporter/Tao.OpenGl.DLL
> ----------------------------------------
> Tao.Platform.Windows
>     Assembly Version: 1.0.0.5
>     Win32 Version: 1.0.0.5
>     CodeBase: file:///F:/WoT%20poking%20around/TankExporter/Tao.Platform.Windows.DLL
> ----------------------------------------
> Tao.FreeGlut
>     Assembly Version: 2.4.0.2
>     Win32 Version: 2.4.0.2
>     CodeBase: file:///F:/WoT%20poking%20around/TankExporter/Tao.FreeGlut.DLL
> ----------------------------------------
> System.Numerics
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.9032.0 built by: NET481REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
> ----------------------------------------
> 
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.
> 
> 

I tried relaunching multiple times to select a different folder or simply declining the request for a path, but the same error appeared. The app seemingly crashes after "Adding Nodes to TreeView Lists (01)". Even if I were to try and use the current 1.13.0.1 build of WoT the app wouldn't let me.

**Comment by Williamsilliam** [comment]
Yeah im getting the same problem, just with v 1.25.0, I tried similar things and the app still wouldn't open.

**Comment by Stromy08** [comment]
it also broke for me now that the game updated

**Comment by ETnannn** [comment]
the same problem, have you solved it?

**Comment by ETnannn** [comment]
> 是的，我遇到了同样的问题，刚刚使用 v 1.25.0，我尝试了类似的操作，但应用程序仍然无法打开。

 the same problem, have you solved it?

**Comment by mikeoverbay** [comment]
closing this as its fixed.
