### ISSUE TITLE
Guns bug

### ISSUE THREAD

**Issue by adadada19** [mikeoverbay/TankExporter#107]
Any models that were added to guns don't show in-game, but showing in Tank Exporter, what can it be?

**Comment by nazref** [comment]
do you use gun_ prefix or _gun subfix(idk if i said that correctly)

**Comment by adadada19** [comment]
I'm using "gun_"

**Comment by nazref** [comment]
welp im out

**Comment by mikeoverbay** [comment]
sorry.. I've been out for months with a injury to my spine.
Maybe the texture paths are wrong in the .visual file
