### ISSUE TITLE
Normal maps fail to extact to .png

### ISSUE THREAD

**Issue by Fr3dBear** [mikeoverbay/TankExporter#11]
Some normal maps such as turret/hull/gun fail to extract correctly leaving a not empty file but no normal map.
![image](https://user-images.githubusercontent.com/6440741/66363211-7837f000-e953-11e9-9a74-9fbb7eb062ef.png)
Some failed examples:
WZ-132-1: Hull, Turret
WZ-111-5A: Hull, Gun, Turret
WZ-121: Hull, Gun, Turret
Sheridin: Chassis, hull, gun

.dds source files are correct

**Comment by mikeoverbay** [comment]
Hi.. I'll look in to this as soon as I can.
I'm under pressure to get an app written for my wife's company.
Thanks for pointing it out.

**Comment by Fr3dBear** [comment]
No rush, love the tool.

**Comment by mikeoverbay** [comment]
I found the problem...
The normal maps for these tanks have no values in the red channel.
As you know each color = RGBA channels.. 
R is used as the alpha in all tanks BUT the ones you listed.
During the conversion from the ANM map to a normal tangent map, I se the green and alpha to calculate the y axis and after, I place the red channel in to the alpha. 
RGB s the tangent values.. R is moved to Alpha before the conversion and becomes the transparency/alpha.
The normal maps should still work in any 3D app.
If you want to fix them in the shader.. Its not hard.
Go to Edit Shaders..
Pick the ConvertNormaMap_shader on the list at the bottom.
FInd this part:
   if (convert == 1)
    {
        color_out.rgb =  tn.rgb*0.5+0.5;
        **color_out.a = m.r;**
    }
    else
...
...
and changed the color_out.a = m.r;
to 
color_out.a = 1.0;
That will force the alpha to 1.0 for all normal map conversions.

**Comment by mikeoverbay** [comment]
Because I have not heard a replay back.. I'm closing this issue.
