### ISSUE TITLE
I cannot export the 3d model (FBX file) of Skoda_T_56.

### ISSUE THREAD

**Issue by akip0612** [mikeoverbay/TankExporter#117]
All other tanks can be exported as FBX, but only Skoda T56 files are not generated.
I want to output this tank with a 3D printer, but I can't do it. Can someone who can export in FBX please share the file with me?

**Comment by mikeoverbay** [comment]
This should work.
[Cz14_Skoda_T-56.zip](https://github.com/user-attachments/files/16530342/Cz14_Skoda_T-56.zip)
