### ISSUE TITLE
Fails to load Decal textures

### ISSUE THREAD

**Issue by BioHZ** [mikeoverbay/TankExporter#12]
Program can't find the path wot_temp\decals\maps\decals_pbs. Verifying integrity of WoT files and uninstalling and reinstalling Tank Exporter fails to fix this.

**Comment by mikeoverbay** [comment]
Hi there..
Windows has a nasty habit of deleting the contents of that folder.
What you need to do is in TE under the files/setting menu.. click "Clear Temp Folder".
This will force Tank Exporter to rebuild all the data.
If you use CCleaner, add an exemption for wot_temp. Windows defender has no exemption settings.
If this works, let me now so I can close this issue :)

**Comment by BioHZ** [comment]
Part of the problem is that the program effectively freezes at this stage, rendering me unable to open the settings menu. If there is a way to access settings without having the program load the resources, I do not know if it.

**Comment by mikeoverbay** [comment]
Well that is a problem!
I recommend deleting everything in the wot_temp folder and starting Tank Exporter to rebuild the data.
The path to the folder is this :

C:\Users\CURRENT_USER\AppData\Local\Temp\wot_temp

You may need to unhide the AppData folder.. Google it for the version of windows you are using.

**Comment by mikeoverbay** [comment]
Also... Id [disable Storage Sense]([url]https://winaero.com/blog/disable-storage-sense-delete-temporary-files-windows-10/(url)).
It cleans out a lot of temp files once a month.

**Comment by BioHZ** [comment]
Clearing out the wot_temp folder manually fixed the issue. Thank you for helping.

**Comment by mikeoverbay** [comment]
Glad to be of service :)

**Comment by mikeoverbay** [comment]
I'm going to add some code to trap that missing decal exception as it seems to happen a lot.
I'll have a new version 109 out probably in a few hours. :)

**Comment by mikeoverbay** [comment]
I added the code do deal with the missing decal folder and also fixed a bug with shadow depth preview :)
