### ISSUE TITLE
Steel Hunter models

### ISSUE THREAD

**Issue by HMarci2007** [mikeoverbay/TankExporter#120]
Hi, 
it's not a bug or a problem, but where can I find **Steel Hunter BattleRoyale tanks**? In the game's res folder, _(World_of_Tanks\res\packages\vehicles_level_01.pkg\vehicles\french\)_, there is _F43_AMC_35_SH_, which is _arlequin_ in SteelHunter, but in TankExporter, that is not there. I tried refreshing the program, but I couldn't find the model. Any ideas?
TIA
-HMarci

**Comment by mikeoverbay** [comment]
They have parts of the tanks spread all over.
You can use my https://github.com/mikeoverbay/PKGexplorer tool and search all pkg.
go to explore and type what you want. * is wild card. without it, it looks for an exact match.

**Comment by mikeoverbay** [comment]
I can't find it. Its not showing in my app. interesting.

**Comment by HMarci2007** [comment]
Ahh thanks, I found it easily with the PKFexplorer. 
It works perfectly. 

If anybody need them: go to "_vehicles_level_01.pkg_", and the tanks that have "_SH_" _[SteelHunter]_ at the back of their names are the steel hunter ones. Then, in "_normal_", "_lod0_", the "_primitive_processed_" is the 3D file. It opens in the model viewer, and then you can hit "_export FBX_".

**Comment by mikeoverbay** [comment]
Cool... I'll see if i can add them to TE later.
