### ISSUE TITLE
Won't load Obj. 430

### ISSUE THREAD

**Issue by hydratioNx99** [mikeoverbay/TankExporter#123]
I wanted to export the Obj. 430 model but when I click on load it says "working" for some time and just loads nothing.
It loads other tanks just fine though.
I think the problem might be that the primitives and textures are located in "res/packages/shared_content-partX" instead of "res/packages/vehicles_level_09-partX"

**Comment by hydratioNx99** [comment]
Other tanks that don't load aswell:
Obj. 777 II
Pz. V/IV
Jagdtiger

**Comment by mikeoverbay** [comment]
Let me see whats up.

**Comment by mikeoverbay** [comment]
That was exactly the issue. the way i did a last ditch search was wrong. This new version fixed the issues. I loads all the tanks listed here!
Good job guys!
Reinstall 142 or update to it.

**Comment by hydratioNx99** [comment]
oh nice, thank you!
