### ISSUE TITLE
Why am I having this problem even though I selected the correct game file?

### ISSUE THREAD

**Issue by Aker490** [mikeoverbay/TankExporter#124]
https://streamable.com/2im04q

**Comment by Stromy08** [comment]
which version are u using?

**Comment by Aker490** [comment]
> which version are u using?

latest

**Comment by Stromy08** [comment]
Maybe try a different version. I'm not sure what version I tried in but it worked for me just now.
And also did it work for u before?

**Comment by Aker490** [comment]
> Maybe try a different version. I'm not sure what version I tried in but it worked for me just now. And also did it work for u before?

Do you have the old version? I just used it for the first time.

**Comment by Stromy08** [comment]
I don't remember right now, my pc is off so I can't check. But mabye try running a different version or something

**Comment by Aker490** [comment]
> I don't remember right now, my pc is off so I can't check. But mabye try running a different version or something

ok

**Comment by Aker490** [comment]
> I don't remember right now, my pc is off so I can't check. But mabye try running a different version or something

Do you know how to fix the problem of not being able to export Fbx?

**Comment by Cerberus50** [comment]
delete res mod 1.25.1.0  folder and try again

**Comment by Aker490** [comment]
> Do you know how to fix the problem of not being able to export Fbx?

Thank you very much, now I can export.

**Comment by Aker490** [comment]
> delete res mod 1.25.1.0 folder and try again

Thank you very much, now I can export.

**Comment by mikeoverbay** [comment]
So sorry. I have been working on TE.
I just update it. Follow so you get notified.
Are there any other problems?
Thanks guys for helping out!
