### ISSUE TITLE
Forum don't send email verification 

### ISSUE THREAD

**Issue by Anzuch4ng** [mikeoverbay/TankExporter#126]
Hey! It's cool that you guys put software behind the closed forum, but I can't register / make an account since it doesn't send an activation link to the email provided during registration process (spam folder is also empty). 

Send help

**Comment by mikeoverbay** [comment]
i'll do it for ya now. I don't know why it isn't sending. I've tested it a few times..

**Comment by Anzuch4ng** [comment]
It's working now, thank you for quick response!
