### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by BioHZ** [mikeoverbay/TankExporter#13]
While loading, and getting to creating nodes by tier (specifically 08), an error occurs causing the program to stop. Object reference not set to instance of object.

**Comment by mikeoverbay** [comment]
Try deleting everything in the wot_temp folder and restarting Tank Exporter.
Or.. go to the File menu in Tank Exporter, look for 'Clear Temp Folder' and click it. That should clear out any data that is conflicting with the new WOT update.
They probably removed or added a tank and its causing TE to crash because it cant find the image of it anymore.

**Comment by BioHZ** [comment]
Deleting the temp folder results in the program still attempting to load the presumably deleted tank, so it still fails to load

**Comment by mikeoverbay** [comment]
I'm trying to duplicate the problem here....
I'll let you know as soon as I find out anything.

**Comment by mikeoverbay** [comment]
I deleted the wot_temp contents and restarted TE.. It rebuilt everything and loaded with no errors.
Can you post the top 10-15 lines of the stack trace of the exception being thrown?

**Comment by BioHZ** [comment]
I'm not too familiar with what that is, but I hope this helps
When opening the details, this is included
System.NullReferenceException: Object reference not set to an instance of an object.
   at Tank_Exporter.frmMain.store_in_treeview(Int32 i, TreeView& tn)
   at Tank_Exporter.frmMain.load_tabs()
   at Tank_Exporter.frmMain.frmMain_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by mikeoverbay** [comment]
Yep.. That's what I was looking for. Its the call stack.
The error is happening when it tries to add a tn (table node) to the tree view on one of the tabs.
I'll need to add some code to give more info on whats crapping out.
Its late here and I'm dead tired.. I'll get on this first thing in the morning and have a version for you to try that hopefully will give us more info on why this is happening.

**Comment by mikeoverbay** [comment]
I build a version that might help trap this error and give us more info on what's happening.
Uninstall and install this : https://github.com/mikeoverbay/TankExporter/blob/master/TankExporter_110_DEBUG.msi
Let me know what is displayed in the text box that pops up when it crashes (if it does pop up).

**Comment by BioHZ** [comment]
crashed getting type: Tier8 Index2
package E:\Games\World_Of_Tanks_NA/res/packages/vehicles_level_08_hd-part2.pkg
png_path gui/maps/icons/vehicles/ussr-R27_SU-14.png
It seems like they did remove a tank as you said.

**Comment by BioHZ** [comment]
Also missing is the icon ussr-R119_Object_777.png and ussr-R95_Object_907.png. However, this debug version does not freeze when it cannot load certain files, which is nice.

**Comment by mikeoverbay** [comment]
I have those files in my gui.pkg.
They are located at gui/maps/icons/vehicle/
Check your gui.pkg and see if those pngs are missing.
You can use my [PKG Explorer](https://github.com/mikeoverbay/PKGexplorer) tool if you want.

**Comment by mikeoverbay** [comment]
Now that we have a working app.. sorta.. You can go to file.. show log file. It should list all the tanks found, You could look that file over and see if it has any thing about missing tanks.

**Comment by mikeoverbay** [comment]
Did you find any thing on why these tanks are not showing up?
I'd like to close this issue but I want to fix what ever is causing the problem.

**Comment by BioHZ** [comment]
Apologies for late reply.
My log file displays total tanks found as 376, assumedly due to the rest of the tanks on the tiers of the missing tank icons failed to load, as evidenced by the missing tanks being the only tanks in their tiers (Tier 8, 9, and 10)
I think the problem may have been that World of Tanks was not updating, so I will update it now and see if that makes a difference.

**Comment by BioHZ** [comment]
Updating World of Tanks fixed the problem. Thank you so much for helping.

**Comment by mikeoverbay** [comment]
No big.. :)

**Comment by AlexG7796** [comment]
Hi.
I've started to get right the same error message today, 3 years later from this thread. Is there some permanent work around?


**************  **************
System.NullReferenceException: Object reference not set to an instance of an object.
   в Tank_Exporter.frmMain.store_in_treeview(Int32 i, TreeView& tn)
   в Tank_Exporter.frmMain.load_tabs()
   в Tank_Exporter.frmMain.frmMain_Load(Object sender, EventArgs e)
   в System.EventHandler.Invoke(Object sender, EventArgs e)
   в System.Windows.Forms.Form.OnLoad(EventArgs e)
   в System.Windows.Forms.Form.OnCreateControl()
   в System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   в System.Windows.Forms.Control.CreateControl()
   в System.Windows.Forms.Control.WmShowWindow(Message& m)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   в System.Windows.Forms.ContainerControl.WndProc(Message& m)
   в System.Windows.Forms.Form.WmShowWindow(Message& m)
   в System.Windows.Forms.Form.WndProc(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
