### ISSUE TITLE
Issues using fbx in Fusion 9 with OpenGL Renderer

### ISSUE THREAD

**Issue by ml1969** [mikeoverbay/TankExporter#15]
Hi,

first of all I will say THANK YOU for this great tool. I was looking for so long time.... Really GREAT!!!!
Second I have to say I´m from germany and sometimes it will be difficult to understand my english:

Ok what I do is to import the fbx file in BlackMagic fusion9 as fbx file.
I can see the tank,  everything is fine as long as I use the software renderer. But with larger scenes it takes a long time. My last composition lasted 2 hours. 15 minutes with the OpenGL renderer.
But the cannon, chasis and chains are not displayed correctly.
I have attached a few screenshots to show what it looks like.
What am I doing wrong???

Edit: I have to say that I tried to modify the shader as you suggest in an other issue..... 
Michael

![screenshot_tank_exporter_1](https://user-images.githubusercontent.com/10650988/76018195-23a79980-5f20-11ea-9721-e153c5839427.png)
![screenshot_tank_exporter_2](https://user-images.githubusercontent.com/10650988/76018203-27d3b700-5f20-11ea-8462-a3c7c11924d1.png)
![screenshot_tank_exporter_3](https://user-images.githubusercontent.com/10650988/76018208-2b673e00-5f20-11ea-932e-90c1538b8165.png)
![import_fusion](https://user-images.githubusercontent.com/10650988/76018226-2e622e80-5f20-11ea-9d29-fea2be56be0a.png)
![sceene_fusion](https://user-images.githubusercontent.com/10650988/76018234-302bf200-5f20-11ea-8179-904acf01cb38.png)

Edit 2:
I also tried diffrent settings with the Autodesk fbx Converter, no succes
And if I open the fbx file in windows it looks quiet the same
![windows](https://user-images.githubusercontent.com/10650988/76023831-450d8300-5f2a-11ea-90ba-9a75680b1219.png)

**Comment by ml1969** [comment]
hi,
I found the solution.
I have to disable importing "Vertex Colors" in Fusion.
Than all looks nice.
Now I have to take a look how can I use the "Vertex Colors" to use it...
This issue can be closed...

Thanks again for this great tool.
Michael

**Comment by mikeoverbay** [comment]
Glad you got it sorted out Michael.
