### ISSUE TITLE
All tanks show up as black (no textures)

### ISSUE THREAD

**Issue by red1134** [mikeoverbay/TankExporter#16]
Whenever I load a tank, it shows up as pure black and I can't see the texture.

**Comment by mikeoverbay** [comment]
If you are using an INTEL video card, there are issues with them.
The shaders don't work well with Intel's OpenGL.
You could try setting Tank Exporter to basic shading under the File Menu and see if that works.

**Comment by red1134** [comment]
Using AMD Radeon RX580. Changing some of the settings around made the textures appear but still difficult to see the textures.

**Comment by mikeoverbay** [comment]
I don’t have a AMD card so it’s impossible for me to debug these issues. My guess is the shaders have something in them AMD OpenGL doesn’t like. AMD is a lot more picky with the code.

**Comment by red1134** [comment]
After changing some settings I can see the textures good enough to see my edits. 

On an unrelated note, where is the decals folder located at (location of wot_temp)? Every time I restart this program it thinks that the decal folder is missing. I used to just copy and paste the folder back in before you added the check for the folder and now I can't remember its location. I don't like waiting and would like to continue to just paste the folder back in to save time.

**Comment by mikeoverbay** [comment]
Windows 10 deletes the decals folder. 
It does it when it runs it’s clean up automated cleanup crap. 
Also. Other apps like CCleaner will too unless an exemption is added.

**Comment by Stahlhelm-TV** [comment]
> 
> 
> After changing some settings I can see the textures good enough to see my edits.
> 
> On an unrelated note, where is the decals folder located at (location of wot_temp)? Every time I restart this program it thinks that the decal folder is missing. I used to just copy and paste the folder back in before you added the check for the folder and now I can't remember its location. I don't like waiting and would like to continue to just paste the folder back in to save time.

What exactly did you change so you were able to see it? Im using a RX580 too

**Comment by mikeoverbay** [comment]
Is this resolved?

**Comment by Stahlhelm-TV** [comment]
i still haven't managed to find a solution for it. If you know a way i can help you then you can message me. i would be happy to help with the amd shader issue.

**Comment by mikeoverbay** [comment]
Tank Exporter has a built in shader editor.
Press F9
There are a lot a shaders but the one you need to fix is the tank_shader.
The Compile button on the bottom right Compiles the shader and if any errors are thrown, a window will pop up.
If no errors are thrown, Its going to be hard to find the issue.
If you do find the issue, it probably will show up in other shaders.
Once all the shaders are fixed (If you get them fixed) I can replace the shaders in my project and they will be permanent.
The shaders located at C:\Program Files (x86)\Coffee_\Tank Exporter\shaders
If you get them working, let me know and I'll get my email addy to you and you can send me a zip of the shaders.

**Comment by mikeoverbay** [comment]
If you don't know how to write shaders, just finding the error by compiling the tank_shader and posting the error here would help me fix the shader to work with AMD.
Thanks for offering to help!

**Comment by Stahlhelm-TV** [comment]
Well i do not receive an error. And i don't know how to change anything in there too. The other option i could offer would be via remote control so you can try until you found it.

Add me on discord if you got any other idea or if you want to discuss about the remote host way.
Jamos#2208

**Comment by Stahlhelm-TV** [comment]
Something which i thought of too would be an option to export all camos too at the same time. Maybe its already in there and i missed it but thats something which would be usefull to for a complete dump. And thanks for the fix, it looks like everything is working.

**Comment by mikeoverbay** [comment]
Its near impossible when it doesn't show any error.
Try running TE in Simple Light mode.. Its under file/settings -> UI and View Settings.

**Comment by Stahlhelm-TV** [comment]
> 
> 
> Its near impossible when it doesn't show any error.
> Try running TE in Simple Lighting mode.. Its under file/settings -> UI and View Settings.

I'll give it a try thanks

**Comment by Jephawk** [comment]
I have exactly the same problem with an Asus Vega 56 card.
Textures are show only in black color.

With TE in Simple Lighting mode, it's the same as Show Textures off.
Textures are not displayed.

The program works fine on my second computer with GeForce GTX970.

By the way, you make a great job!

**Comment by Jephawk** [comment]
Initial load 4TP Tank
![image](https://user-images.githubusercontent.com/67932086/86997475-2c350880-c17c-11ea-864e-da2975bb1250.png)
With Simple Lighting
![image](https://user-images.githubusercontent.com/67932086/86997652-9b126180-c17c-11ea-958b-02362fc3aa2b.png)
With Show Textures Off
![image](https://user-images.githubusercontent.com/67932086/86998033-85ea0280-c17d-11ea-9417-f17be8afb381.png)

**Comment by mikeoverbay** [comment]
Its interesting it doesn't draw the tracks at all in the first image.
No idea. AMD is very strict with its GLSL format.

**Comment by mikeoverbay** [comment]
OK.. I found something odd.
The tank_fragment.glsl and tank_vertex.glsl have 3 characters at the start that are not ascii.
Why or how they got there I have no idea.
I'm going to rebuild 114. look for the version updated today.
I am not releasing a new version until I make sure all shaders don't have these extra characters.

**Comment by mikeoverbay** [comment]
The odd characters are the Byte Order Mark. EF BB BF hex
Some apps used these.. GLSL does not and why there are inserted I have no idea.
I am going to check that my built in editor does not insert these.

**Comment by Jephawk** [comment]
Sorry, but not much improvement!
![image](https://user-images.githubusercontent.com/67932086/87259403-17f15400-c479-11ea-997f-e6d6ead6311a.png)

**Comment by mikeoverbay** [comment]
I was so hoping that was the issue.
I used Khronos' glslangValidator to check the shader. I showed no errors other than the 3 BOM characters.
I need to find someone fluent in GLSL that owns a AMD card that's willing to help. That or buy a used one.
I will get this working for you all if there is a way!!

**Comment by mikeoverbay** [comment]
I posted on the NA forums asking for help from someone that knows GLSL and owns a AMD card.
Hopefully, I'll get someone to help.

**Comment by Jephawk** [comment]
Thank you very much for the effort, but luckily for me, I have a second computer with a GeForce and it works very well !! If there is another test to do, I'm here !!

**Comment by mikeoverbay** [comment]
> Thank you very much for the effort, but luckily for me, I have a second computer with a GeForce and it works very well !! If there is another test to do, I'm here !!

I"m glad you can use it with out the shading problem.
There as been no replies at the NA forums where I asked for help.
I would by a AMD RX580 card but I just can't afford it on my fixed income. They are going for 100 bucks on E bay.
Some of the shaders use old deprecated 1.1 instructions. This is not suppose to be an issue as neither nvida or amd has removed them.
If 3 people wanted to donated 40 bucks, I will use that money to buy a card I can test with. That would cover the card and shipping costs at E bay.

**Comment by red1134** [comment]
I have a second RX580 (the 4GB version) that I never bothered to try and sell. I doubt it's worth much anymore if the 8gb version only goes for $100. I could pop that card in my PC to see if the issue persists and if it does I could just donate that old card to you for testing.

**Comment by mikeoverbay** [comment]
> I have a second RX580 (the 4GB version) that I never bothered to try and sell. I doubt it's worth much anymore if the 8gb version only goes for $100. I could pop that card in my PC to see if the issue persists and if it does I could just donate that old card to you for testing.

**That would be fantastic!** Don't need the extra mem.. its just to test shaders.
let me know and I'll get me address to you :)

**Comment by mikeoverbay** [comment]
I guess donating the AMD card isn't going to happen..
When I can, I'll buy a RX580.

**Comment by red1134** [comment]
Oh sorry! I've been quite busy lately and it slipped my mind. I'll see what I can do, I've had issues trying to ship things before.

**Comment by mikeoverbay** [comment]
Its all good but I was starting to wonder what happened.
If you email me, I can send you my address.  I don't dare post it for the world to see.

**Comment by AAI-Ghoul** [comment]
Hello, Intel user here. I am experiencing a similar issue (latest version, I downloaded and installed everything today). I am having the overly bright issue. I noticed when I disabled bloom, the texture became a flat grey. The old version used to work then I exported one tank and the issue started persisting. As well, when I reinstalled, the process was much faster than I remember it being, albeit I did not restart between installations. Not sure if those last two pieces are relevant but it might have something to do with my installation.

**Comment by AAI-Ghoul** [comment]
What I also noticed is that when I enable and disable textures on the model I get when I disable bloom, there is no visual difference. Could this be something with how the textures are loaded? Thank you.

**Comment by red1134** [comment]
Sorry for the long delay about the graphics card, had some stuff cause COVID. I'm afraid to say it doesn't actually work anymore, I tested it in my PC.

**Comment by mikeoverbay** [comment]
Closing this issue as there has been no fixes found for AMD hardware.
Sorry guys.
