### ISSUE TITLE
View 3D Styles in _skins subfolder

### ISSUE THREAD

**Issue by Kawo83** [mikeoverbay/TankExporter#17]
Hello, 

if it is already possible, I can't find it. 
It would be very nice to select the different styles in the tank subfolder _skins. After selecting the skin it would be possible to extract the chosen skin to res_mods folder and use it ingame.

The _skins folder appear in the folder when extracting to res mods, but its not chosen.

Thanks for help!

**Comment by mikeoverbay** [comment]
Copy the files from skins in to the base tanks folder. It’s the only way to view them in tank exporter. If you edit them, just copy them back to skins when done writing the files from tank exporter. 
Sorry for the late delay. Been sick as hell.
