### ISSUE TITLE
A normals/lighting bug is produced once exporting and importing any FBX.

### ISSUE THREAD

**Issue by vontamar** [mikeoverbay/TankExporter#2]
I've found out there's a hard-coded bug somewhere in the converter, not sure if it's the primitives converter or the FBX converter tho.
You don't need to modify anything in the model. To reproduce the bug, just "Export FBX" of any tank, and then import the very same file back by using "Import FBX" and then "Write Primitives" to the actual game folder, re-select the tank in the garage and see the difference: Where comes the lighting from the sun, is actually dark. Any model exported & imported by the TankExporter will be affected because no 3rd party software were involved while producing the bug.

![bug](https://user-images.githubusercontent.com/24723374/38649216-09541a3a-3dfe-11e8-8082-a1d04bd477b5.jpg)
Look in the picture above and see the actual difference.

**Comment by mikeoverbay** [comment]
Ill check this right now...

**Comment by mikeoverbay** [comment]
I just tried this with the T110E4 and its renders fine following your instructions.
Is this happening with all tanks?

**Comment by mikeoverbay** [comment]
OK.. I found the problem.. Its the surface normals. I fixed this issue long ago and not sure why its happening again but I'll sort it out.. Keep an eye out for version 32.
