### ISSUE TITLE
Shader/Render Problem with 3ds Max 2021

### ISSUE THREAD

**Issue by Stahlhelm-TV** [mikeoverbay/TankExporter#20]
Here i am again, so when i use your tanks in 3ds Max 2021 and i set the Render Method to High Quality the tank illuminates completely white. I have tried with a few other files from me and all of them work without this issue so this must be happening while exporting them.

AMD Radeon 580 GPU

Screenshot:
![before-edit](https://user-images.githubusercontent.com/27901510/86496669-bb0de380-bd7e-11ea-9ce0-302fd7b99878.jpg)
![after-edit](https://user-images.githubusercontent.com/27901510/86496668-b9dcb680-bd7e-11ea-88a3-c8e7a14e98b4.jpg)

Thought i open a new issue since its a new problem

**Comment by mikeoverbay** [comment]
Did you find the problem?
I don't have that issue here but Ill double check.

**Comment by Stahlhelm-TV** [comment]
Until now i haven't found the problem now. But i guess it must be happening while exporting and owning a AMD card somehow.

**Comment by mikeoverbay** [comment]
Try this re-build of 114 and see if the tanks are shading ok.
I found some odd characters at the start.

**Comment by mikeoverbay** [comment]
I am closing this.. I am going to get a used AMD card at some point and sort out the issues with the shaders.
