### ISSUE TITLE
Support for Camos at Dump?

### ISSUE THREAD

**Issue by Stahlhelm-TV** [mikeoverbay/TankExporter#21]
Is there a way you could add an option to Dump all camos along with all tanks? Or a standalone option to Dump all of them into a folder with the tank names like with the current dump and then merge them together manual?

**Comment by mikeoverbay** [comment]
Let me think about this.
Every camo is created using data from the tanks xml file and the DDS that's used to mix with.
A lot of this data is loaded when the tank is loaded. That is one reason dumping all the tanks is rather slow.
There is a shader just for creating the Camos using this data. When you select the camo menu item, TE creates a bunch of thump nail images for the camo buttons using that shader. Writing a few dozen full size camo textures is going to drastically slow down dumping all tanks.
Let me think about this more....

**Comment by Stahlhelm-TV** [comment]
Understood, its a fair point. Was just and idea/question about possibility. If you want you can close this issue unless you want to add something else.

**Comment by mikeoverbay** [comment]
I am closing this as it has been added to TE.
