### ISSUE TITLE
Tank Gun Misplacement

### ISSUE THREAD

**Issue by Stahlhelm-TV** [mikeoverbay/TankExporter#23]
Found this Gun Misplacement on the G45_G_Tiger, Destroyed Model.

Modification: 
Gun_01
Turret_01

![Annotation 2020-07-04 144052](https://user-images.githubusercontent.com/27901510/86512675-7167dc00-be04-11ea-8102-7af68035bc5f.png)

**Comment by mikeoverbay** [comment]
Ouch! 
Let me try loading that..
Yep... Same thing here. Very strange. Ill have to have look the visual over for the turret and gun.

**Comment by mikeoverbay** [comment]
So strange.. I'm not seeing any thing wrong in the visual files.
I'll mess with it after I fix the other issues.

**Comment by Stahlhelm-TV** [comment]
Sure, no rush 😄

**Comment by mikeoverbay** [comment]
This is why the gun is in the wrong spot... It gun_01 is literally in the wrong location. The vertices are of this model are not in the same location as all other models.. 
The only way to fix this is load the FBX in 3DS and translate the model in Z (Y in world of tanks)
I could add some hack code but that risks screwing up other models.
It looks like it should be moved by -1.19869 in Y.
If you want me to do this for you, I can... Let me now.
This image shows that gun_01's model is not in the right location in Y (Z in 3DS max)
![GunModels](https://user-images.githubusercontent.com/15058778/88678121-1dc37800-d0bc-11ea-891a-53a0666491eb.png)

**Comment by mikeoverbay** [comment]
I used my PKG Explorer program to find and display the models.

**Comment by mikeoverbay** [comment]
OK.. Extract this in to the current res_mods.
It has the fix for the G45_G_Tiger crashed gun.
After.. Load the G_45_G_Tiger in tank exporter and export the FBX to place were you extracted all the other tanks.
This should fix that floating gun issue. If you need more help, let me know :)

[G45_G_Tiger_Patch.zip](https://github.com/mikeoverbay/TankExporter/files/4989574/G45_G_Tiger_Patch.zip)

**Comment by Stahlhelm-TV** [comment]
Thanks, appreciate it

**Comment by Stahlhelm-TV** [comment]
Closing issue due to fix available

**Comment by Stahlhelm-TV** [comment]
Closing issue due to fix available

**Comment by mikeoverbay** [comment]
You'er welcome...
I'm going to let Wargaming know about this.. I doubt they will fix it but I can try.
