### ISSUE TITLE
Question about Quality and Detail

### ISSUE THREAD

**Issue by Official-Husko** [mikeoverbay/TankExporter#24]
Are the tanks which are being exported from Tank Exporter the same Quality as the Tanks Ingame?

Is there a way to get the good detailed tracks or are they being exported already because in 3ds max and Tank Exporter they looked like rubber bands wrapped around the tank wheels and not like real tracks. Is there a way to change that?

From This: 
![From This](https://user-images.githubusercontent.com/27901510/86520635-13101d00-be47-11ea-9e23-dc947d543391.jpg)

To This: 
![To This](https://user-images.githubusercontent.com/27901510/86520654-4d79ba00-be47-11ea-918d-af8041857328.jpg)

Sorry for opening so many Issues but i thought that its the best way since there are different questions and problems.

**Comment by mikeoverbay** [comment]
I spent a month trying to sort out how the create the nurb line that they use to guide the path of the track sections.
I gave up as I never was able to do it correctly.
<a href="https://imgur.com/3eIDzk5"><img src="https://i.imgur.com/3eIDzk5.jpg" title="source: imgur.com" /></a>

**Comment by mikeoverbay** [comment]
If we can get the shaders to work, the tracks look pretty good.
You could try setting the rendering to "Simple Lighting" under File/Settings -> UI and View Settings.

**Comment by Stahlhelm-TV** [comment]
> 
> 
> If we can get the shaders to work, the tracks look pretty good.
> You could try setting the rendering to "Simple Lighting" under File/Settings -> UI and View Settings.
> That will bypass the tank_shader.

Im not sure if simple lightning should look like this but in that case i do prefer texture less. With Simple Lightning i can't really see what is what that good.
![Annotation 2020-07-07 010757](https://user-images.githubusercontent.com/27901510/86663728-4f31b200-bfee-11ea-9903-6c6300a5a2da.png)

But still thanks, was worth a try regardless.

**Comment by Stahlhelm-TV** [comment]
> 
> 
> I spent a month trying to sort out how the create the nurb line that they use to guide the path of the track sections.
> I gave up as I never was able to do it correctly.
> This image is from when I was trying to find help getting it to work. I could not find anyone that knew anything :(
> [![](https://camo.githubusercontent.com/ee94915ffb746f40bed660e5b3d2f7be47d8b9b8/68747470733a2f2f692e696d6775722e636f6d2f336549447a6b352e6a7067)](https://imgur.com/3eIDzk5)
> [![](https://camo.githubusercontent.com/0e2a208eff932f5cfc5947a6fe70e8586d09c2ba/68747470733a2f2f692e696d6775722e636f6d2f6e524c7a5641772e6a7067)](https://imgur.com/nRLzVAw)

Would it be Ok for your if i would ask around in a few forums to see if somebody knows anything? About the tracks part.

**Comment by mikeoverbay** [comment]
No.. Its not suppose to look like that. Even the terrain isn't right and that's a different shader.

Yes.. Its oh to hunt around. Maybe some knows something.

**Comment by Stahlhelm-TV** [comment]
Alright i'll ask around a bit

**Comment by red1134** [comment]
As for the actual track texture itself, it uses an alpha mask to get the actual cutout. As for the realistic physics, it's likely something outside what the model data will provide.

**Comment by mikeoverbay** [comment]
> As for the actual track texture itself, it uses an alpha mask to get the actual cutout. As for the realistic physics, it's likely something outside what the model data will provide.

The data for how the tracks are created and physically move are in the tanks .xml file. Limitations and reactions. Segment count and other info.
The nurb line is deformed in real time based on what the tank drives over. The track follows that nurb line.
The math is complicated. Getting the track sections to fit is where I was stumped.
Maybe some time all give it another try.

**Comment by red1134** [comment]
Huh, I thought it was all IK driven...

**Comment by mikeoverbay** [comment]
Closing this issue. If you want to discuss this more.. reopen it.
