### ISSUE TITLE
Messy Upgrade Names / Abort not working

### ISSUE THREAD

**Issue by Stahlhelm-TV** [mikeoverbay/TankExporter#25]
On many Tanks i have seen weird Upgrade names. Take a look at the Photos: 
Also the Abort or X button is not aborting upon hitting it, i still loads the tank.
i only listed a few tanks but im sure i saw more than these. i don't want to be picky its just something i noticed.

MS-1 (R11_MS-1)
![MS-1 edit](https://user-images.githubusercontent.com/27901510/86674476-029fa400-bff9-11ea-9b99-6f3a61dc87be.jpg)

R. Otsu (J01_NC27)
![r-otsu edit](https://user-images.githubusercontent.com/27901510/86675275-cb7dc280-bff9-11ea-9c02-8b99360db16b.jpg)

Medium I (GB03_Cruiser_Mk_I)
![cruiser mk1 edit](https://user-images.githubusercontent.com/27901510/86675367-dfc1bf80-bff9-11ea-940d-a815f9eb925b.jpg)

L. Tr. (G12_Ltraktor)
![ltr edit](https://user-images.githubusercontent.com/27901510/86675330-d6d0ee00-bff9-11ea-8aaa-115fa6098dcf.jpg)

Abort Button not aborting: 
![abort button edit](https://user-images.githubusercontent.com/27901510/86675381-e2bcb000-bff9-11ea-99df-bfe87ade8264.jpg)

**Comment by mikeoverbay** [comment]
The weird names is WoT's doing.. Thats how they are named in the data.. Yeah.. Makes no sense but that's how it is.
Also the order of the check boxes is the order they are stored in the data. More of WoT's messed up crap.
I might be able to sort them. I'll have a look after we get the exporting of all tanks the way you want them.
Cheers!

**Comment by mikeoverbay** [comment]
I should add.. as far as I have ever seen, upgraded hulls are the same as the base hull.. numbering is strange..  it's usually _01 but once in a while you'll see _02. WoT crap again. 
**If you find a tank that actually has more than one hull primitive, let me know.**

**Comment by Stahlhelm-TV** [comment]
> 
> 
> I should add.. as far as I have ever seen, upgraded hulls are the same as the base hull.. numbering is strange.. it's usually _01 but once in a while you'll see _02. WoT crap again.
> **If you find a tank that actually has more than one hull primitive, let me know.**

More than one hull? i never really played WoT im more of a War Thunder guy 😅 
Im not sure if i understand you correctly but if i see something then yes ill let ya know
