### ISSUE TITLE
Opening WOTMOD files to TankExporter

### ISSUE THREAD

**Issue by zhrimpman** [mikeoverbay/TankExporter#26]
I did some research on how to open WOTMOD files to be in TankExporter as .fbx. There are no answers to this so I wonder on how to possibly do this?

**Comment by mikeoverbay** [comment]
Tank Exporter can open WOTMODs.. It can only write them.
You can try unzipping the WOTMOD to the res-mods folder and than try to load that tank.
This wont work however if the primitives_processed file is in the very old format. No models use that in the game anymore.

**Comment by zhrimpman** [comment]
So there is no other way to do this step by step? Alright.

**Comment by BBAA2** [comment]
> So there is no other way to do this step by step? Alright.

well you can rewrite  primitives_processed
