### ISSUE TITLE
i encounter this Issue, i don't know what cause this but, even i reinstall, the error still pop up

### ISSUE THREAD

**Issue by BBAA2** [mikeoverbay/TankExporter#27]
![rewrwetwey](https://user-images.githubusercontent.com/69168413/89220493-de38e680-d5fb-11ea-8c70-55ada9b83370.png)

**Comment by mikeoverbay** [comment]
Get the latest version and also.. clean out the wot_temp folder.
Version 115 is what you want.
windows key + S and then type %temp% and find the wot_temp folder.
