### ISSUE TITLE
An Error Which Crashed

### ISSUE THREAD

**Issue by zhrimpman** [mikeoverbay/TankExporter#28]
Since the World of Tanks update for 1.10, I encountered this crashed message like this:

![image](https://user-images.githubusercontent.com/68905649/89440759-23533a80-d71a-11ea-93da-55551f5d3257.png)

This repeated from Tier1 to Tier10 package.
(Means that it doesn't show the tank list in the tier list).

Can you see how to fix this crash error? I tried to uninstall and reinstall it, and it still doesn't work.

**Comment by zhrimpman** [comment]
Update: I updated the .NET Framework, and it still doesn't work, strange.

**Comment by mikeoverbay** [comment]
Did you get version 115 I released yesterday?
If not.. Try that. It should fix this issue.
WG split the gui.pkg in to two separate files. I added code to deal with that issue.

**Comment by zhrimpman** [comment]
I had the version 114 so I will do it.

**Comment by mikeoverbay** [comment]
Sorry I didn't inform you of the new update.
This should fix it.

**Comment by Jephawk** [comment]
I have the same problem with version 115 and also earlier versions, and for all packages from 1 to 10.
![image](https://user-images.githubusercontent.com/67932086/89717245-7a5b4880-d982-11ea-873c-fbd568f876d1.png)

**Comment by mikeoverbay** [comment]
Jephawk,
You are running version 1.10 of the game?
If you are.. look in the res/packages/ for gui-part1.pkg and giu-part2.pkg.
Version 115 is expecting to find these pkg files.

**Comment by mikeoverbay** [comment]
also.. you may need to clear the wot_temp folder.
Press the windows key and 'S'
Type %temp%
open the temp folder and find the wot_temp folder.. Delete everything inside it.

**Comment by Jephawk** [comment]
Yes it works, Tank Exporter v1.0.0.115 and WOT v1.10.0.2150!
Thank you for your work!

**Comment by mikeoverbay** [comment]
Glad to hear it!
