### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by lost70344** [mikeoverbay/TankExporter#29]
![Screenshot 2020-09-25 115838](https://user-images.githubusercontent.com/71896339/94295179-77161f00-ff26-11ea-8f4f-a60259f6a343.png)

I tried to uninstall and reinstall the program, every time i launch it i get the error

**Comment by mikeoverbay** [comment]
It looks like you have set the path to the game to the wrong location.
I would clean out the wot_temp folder under the File menu.

**Comment by lost70344** [comment]
Ok, I'll try that. Thank you

**Comment by mikeoverbay** [comment]
Did that work?
If so.. please close this issue :)

**Comment by lost70344** [comment]
Yeah, it worked. Thank you

**Comment by mikeoverbay** [comment]
Cool.
