### ISSUE TITLE
Program loading exterior styles and not base versions

### ISSUE THREAD

**Issue by Kwarduk** [mikeoverbay/TankExporter#30]
Hello

I've just come across an issue where I'm trying to load up a vehicle to export it, but it's loading up the vehicle with a style on it, and not the base vehicle, discovered it with the FV4005, the Kranvagn has a similar issue.

![image](https://user-images.githubusercontent.com/74573663/99322017-0379f980-2867-11eb-968d-eb4f4e1cecd6.png)

Is this a bug with the program loading things wrong? As far as I can tell, I can't select the base version of the vehicle and I'm stuck with this version.

**Comment by xGAPMANx** [comment]
Same for me, also happens to Obj. 705A and Progetto 65

**Comment by mikeoverbay** [comment]
Let me look in to this.. Sorry for not getting back sooner.

**Comment by mikeoverbay** [comment]
This is fixed.. Thanks for the feed back guys!

Version 116:
Fixed a bug with TE loading from the _Skins folder if it exist.
Added check box to load from _Skins if it exist.
