### ISSUE TITLE
.Net Framework (Unusual)

### ISSUE THREAD

**Issue by zhrimpman** [mikeoverbay/TankExporter#31]
![error](https://user-images.githubusercontent.com/68905649/101755048-48b9d180-3a89-11eb-913e-b55d62ed2198.png)

Hello,

It's been a while since the last error was told from.

But this one is unusual, I updated my .Net Framework to 4.8 (Lastest from Microsoft) and put the required designated file and setup in the World of Tanks files.

Can you help me solving this error? Thanks.

**Comment by mountainviewsource** [comment]
I experienced the same thing too, can someone help?

**Comment by mikeoverbay** [comment]
Interesting,
I'll have a look and see if I can find the issue.

**Comment by mikeoverbay** [comment]
My guess is the config file messed up for some reason.
First... you will need to make the appdata folder accessible. It s a system folder and locked.
Go to this link if you do not know how to do this.
https://help.ableton.com/hc/en-us/articles/209070509-How-to-access-hidden-folders
Next.. find the Coffee_ folder in appdata.
Mine is located here C:\Users\theco\AppData\Roaming\Coffee_
Your windows user name will be were theco is in that path.
Inside that folder... delete the folders that start with !_Tank_Exporter.
Uninstall and reinstall Tank Exporter version 117
This will replace the config file with a new new one.

Please let me know it that works for you.

**Comment by mikeoverbay** [comment]
There is nothing that needs to be placed in the Wot Folders..
This line is confusing to me.
"and put the required designated file and setup in the World of Tanks files."
Just make sure you set the paths correctly in Tank Exporter.
res_mods path should point to here "C:\Games\World_of_Tanks\res_mods\1.11.0.0" or current game version
And game path to : "C:\Games\World_of_Tanks"

**Comment by mikeoverbay** [comment]
This is the contents of my config file.
<configuration>
  <userSettings>
    <Tank_Exporter.My.MySettings>
      <setting
        name="res_mods_path"
        serializeAs="String">
        <value>C:\Games\World_of_Tanks\res_mods\1.11.0.0</value>
      </setting>
      <setting
        name="shadow_quality"
        serializeAs="String">
        <value>4096</value>
      </setting>
      <setting
        name="selected_light"
        serializeAs="String">
        <value>0</value>
      </setting>
    </Tank_Exporter.My.MySettings>
  </userSettings>
</configuration>

**Comment by mikeoverbay** [comment]
This is whats in the config file.
`<configuration>
  <userSettings>
    <Tank_Exporter.My.MySettings>
      <setting
        name="res_mods_path"
        serializeAs="String">
        <value>C:\Games\World_of_Tanks\res_mods\1.11.0.0</value>
      </setting>
      <setting
        name="shadow_quality"
        serializeAs="String">
        <value>4096</value>
      </setting>
      <setting
        name="selected_light"
        serializeAs="String">
        <value>0</value>
      </setting>
    </Tank_Exporter.My.MySettings>
  </userSettings>
</configuration>`

**Comment by zhrimpman** [comment]
I did what you asked me to, and the error kept popping up as I tried this many times, even uninstall and reinstall the application. And I put my res_mods path connected with the updated World of Tanks files.

So what should I do from here?

**Comment by zhrimpman** [comment]
It works now, thank you for helping me.
