### ISSUE TITLE
i found this error on T-54 Chassis location point also when import the tank, the program said soild no texture

### ISSUE THREAD

**Issue by BBAA2** [mikeoverbay/TankExporter#33]
![gasgasgshh](https://user-images.githubusercontent.com/69168413/104087933-bf6b0a00-5295-11eb-8f2e-f042fb6f9a86.png)
this is after import Fbx 
![gasgasghahahj](https://user-images.githubusercontent.com/69168413/104087940-c85bdb80-5295-11eb-9c03-5356657f4059.png)
also this weird thing happen when i reinstall Tank export
![gsagasgsgah](https://user-images.githubusercontent.com/69168413/104087961-e9243100-5295-11eb-9c58-ab61c6522383.png)

**Comment by mikeoverbay** [comment]
Check out this issue.
It's still not resolved.
https://github.com/mikeoverbay/TankExporter/issues/16

**Comment by BBAA2** [comment]
i found the problem. the program didn't run on high-performance NVIDIA processor so i have to go into the NVIDIA control Panel to set it, that why it cause those issue
