### ISSUE TITLE
Ch41_WZ_111_QL

### ISSUE THREAD

**Issue by karelpak1** [mikeoverbay/TankExporter#34]
I can't find WZ-111 5A Qilin (Ch41_WZ_111_QL). In search menu is only WZ-111 5A (ch41_WZ_111_5A) classic one and one with skin - bamboo on the left side

**Comment by mikeoverbay** [comment]
Yep.. I can see it either.
I'll have a look later and see what I can find out.

**Comment by da7k** [comment]
Adding on to this some other missing tanks like the Edelweiss and Nameless that can be found on the SEA server, also the steel hunter tanks.

**Comment by mikeoverbay** [comment]
Tank Exporter only searches the NA data base for tanks. If these tanks are specific to a region, they will not be found in the NA data base. I can probably add code to use different regional servers with out it being to much work.
Let me look in to it and I'll post back.

**Comment by mikeoverbay** [comment]
I do not know where this Edelweiss is. I is not in the pkg files I have nor is it returned in the data from the wot development site.
The Steel Hunter tanks are probably reskins of other tanks. 
I have not been in the game in weeks so I am not sure what they are.

**Comment by da7k** [comment]
Used pkgexplorer and found the files for the nameless and edelweiss, as well as the SH tanks which has SH suffix in their names.
[pic](https://imgur.com/a/oxHMBDN) hopefully this might help.

**Comment by mikeoverbay** [comment]
There must be a special way to get to these tanks at the dev site:
https://developers.wargaming.net/reference/
I can find these tanks on tankopedia https://worldoftanks.com/en/tankopedia
