### ISSUE TITLE
Problem with FBX export

### ISSUE THREAD

**Issue by Elguajo** [mikeoverbay/TankExporter#37]
Hello, I have a problem with exporting FBX files. 
When exporting, the FBX file does not appear. Only textures in PNG format are exported
If you need additional information please let me know I will add it

**Comment by mikeoverbay** [comment]
Was it working for you before or is this the first time you have exported fbx files?

**Comment by Elguajo** [comment]
> Was it working for you before or is this the first time you have exported fbx files?

Yes, it worked before, but I do not know why I ceased to export...

**Comment by mikeoverbay** [comment]
OK...
check where you are writing the FBX to.
Windows security will block my all from writing to any where that is under system control.
Program files is off limits.
Try running Tank Exporter in admin mode.
Let me know :)

**Comment by Official-Husko** [comment]
i can say that it works for me as "intended" (excluding the known AMD Bug/s)
