### ISSUE TITLE
function:assemble shader error invalid value

### ISSUE THREAD

**Issue by KingdomKo** [mikeoverbay/TankExporter#38]
i get this error every time i open the app, any ideas why?

**Comment by mikeoverbay** [comment]
What error?
I need info.

**Comment by mikeoverbay** [comment]
Post the contents of that window here please.

**Comment by KingdomKo** [comment]
![image](https://user-images.githubusercontent.com/86157421/122667648-cfbfd300-d1ab-11eb-8222-8cb6e75a064d.png)
![image](https://user-images.githubusercontent.com/86157421/122667672-e5cd9380-d1ab-11eb-8ec5-69ff9104bafd.png)

**Comment by KingdomKo** [comment]
these two

**Comment by mikeoverbay** [comment]
Your driver for OpenGL does not support version 4.3.
Press F9 and open the shader editor and change the version to 3.3
So.. From this:
#version 430 compatibility
to this:
#version 330 compatibility
and press the Compile button on the bottom right of the editor window.
If you get no errors, you are good to go. It will save the file and will remain there until an update or you remove it.
Sad thing is.. you will need to do this every time you update Tank Exporter. Good news is.. Tank Exporter is not updated very often as there is little I need or can add to it.
Let me know OK?

**Comment by mikeoverbay** [comment]
Tank exporter should still work even with those errors. Normal is for showing the normals as vectors and gDetail is one of the shaders used for primitives and not tanks.
AMD and Intel video chips have issues with my shader code. I have days trying to fix this. I don't have the hardware to debug on so I gave up.

**Comment by KingdomKo** [comment]
Ok, thanks a lot :)

**Comment by KingdomKo** [comment]
Nothing seems to happen anymore when i press F9, do you know why?

**Comment by mikeoverbay** [comment]
No idea
