### ISSUE TITLE
Treeviews.object

### ISSUE THREAD

**Issue by igorek247** [mikeoverbay/TankExporter#4]
Error message saying Something went wrong adding to the treeviews. Object reference not set to an instance of an object.
Please fix asap. thanks

**Comment by mikeoverbay** [comment]
try deleting the wot_temp folder and restarting Tank Exporter.
Usually that error is caused when the data built when TE starts doesn't match the data grabbed from their API DEV server.

**Comment by igorek247** [comment]
Thanks for getting back at me. New update 56 works great now. Thanks :)
