### ISSUE TITLE
Unsure where to locate the event only tanks (As in the Waffentrager even)

### ISSUE THREAD

**Issue by flagmaggot** [mikeoverbay/TankExporter#42]
Title says it all, what method can be done to locate these tanks that arent located in a tier?

**Comment by mikeoverbay** [comment]
There is no information in the API interface for event and special tanks.
https://developers.wargaming.net/reference/na/wot/encyclopedia/vehicles/#parameters_block
I uses the API to get information on the tanks and if the tank is not there, I can't not get any info on it.
The even and other tanks that are not in the API data are listed in each list.xml in each nations folder in the scripts.pkg file.
scripts.pkg\scripts\item_defs\vehicles\nation\list.xml

One of these days, I may rewrite how tank exporter finds the tank info but it would be a lot of rewriting and I have just not been in the mood to program for months.

**Comment by flagmaggot** [comment]
I may take a look and submit a push.

**Comment by mikeoverbay** [comment]
By all means.. If you can sort out my hacky code that would be cool.
If I had to rewrite this, Id get the data from the scripts.pkg and not from the API site. Everything needed is in there.
May have to look up the game name of the tanks in the translation files but I'm not sure.

**Comment by TheHarryAli** [comment]
Any chance exporting Waffentrager? Now there's one Waffentrager on the tier X list, but it's the random battle version, there's no 3D style on it. But when i searched the vehicles_level_10-part1.pkg file there's 2 folders for waffentrager. One's called "G98_Waffentrager_E100" and the other one is "G98_Waffentrager_E100_TLXXL".
