### ISSUE TITLE
problem with graphics

### ISSUE THREAD

**Issue by pakoscosta** [mikeoverbay/TankExporter#43]
the program works, but when I try to visualize the camouflage, the image pulses and does not show the camouflage. I use windows 10 x64, grapichs nvidia

https://user-images.githubusercontent.com/80840170/140645482-78739ee6-593e-41a3-aecb-53c3300352b6.mp4

**Comment by mikeoverbay** [comment]
Hi..
I just tested Tank Exporter with that tank and there is no issue with camo on my system.
I am using a 660 Ti on Windows 10 x64 as well.
The terrain Is rendering wrong. Is it always like this or only when camo is turned on?
AMD cards don't always work with Tank Exporter but nvidia has had no issues.
Which video board is it?

**Comment by pakoscosta** [comment]
Nvidia gtx950m 
the screen is always like this.  only when I select the camouflage, it starts blinking.  and does not show camouflage.

**Comment by mikeoverbay** [comment]
I have no idea why the graphics are trashed. I can fix what I can't duplicate. Sorry :(
