### ISSUE TITLE
.Net Framework Error Object Reference Not Set to An Instance of An Object

### ISSUE THREAD

**Issue by dron18** [mikeoverbay/TankExporter#44]
![Capture JPG1221](https://user-images.githubusercontent.com/94224283/141637034-2d9465ba-3833-4496-9b9e-2f2870ad3574.JPG)
Previously i use the 119 version until i noticed that there's new update to ver 120 but when i installed the 120 i always get this error when loading the nodes

Anybody can help?

**Comment by mikeoverbay** [comment]
clean out everything in the wot_temp folder.
The path is something like this:
C:\Users\USERNAME\AppData\Local\Temp\wot_temp
You may have to make hidden folders visible.

**Comment by dron18** [comment]
thanks a lot it works! i dont have any idea why some of the files is hidden

**Comment by mikeoverbay** [comment]
Good to hear!
Windows hides user folders unless they are public like downloads, videos and such.
