### ISSUE TITLE
Problems Importing FBX

### ISSUE THREAD

**Issue by MattVincentUK** [mikeoverbay/TankExporter#46]
I am able to load in primitive FBX models into tank exporter. I have issues importing regular FBX models into the program. It goes through the files but then nothing loads.
I've tried converting the FBX to different versions, but nothing changes.

**Comment by mikeoverbay** [comment]
Hey...  sorry for the delay.
So FBX files exported from Tank Exporter will not load or what app?

**Comment by mikeoverbay** [comment]
Tank Exporter will look for parts of a tank in the FBX. It can not loaded FBX files that are not for World Of Tank.
