### ISSUE TITLE
Load primitives_processed error: File Not Found

### ISSUE THREAD

**Issue by Fortirus** [mikeoverbay/TankExporter#47]
I have extract all related to the model files from the packages (via PKG Explorer), but for some reason I can't open it with "Load primitives_processed". 
The log says: "File Not Found :E:/MS-1/vehicles/russian/R11_MS-1/normal/lod0/Chassis.model" (i try to load "Chassis.primitives_processed" file)
But this file is right there! 
![explorer_2022-02-08_16-58-35](https://user-images.githubusercontent.com/25717914/153002545-6ec2a65b-fe51-4f1f-83cf-516b15cebb0b.png)

I tried the same with other parts, tanks and even buildings, move the model folder to the same disk as Exporter, but the result is the same. I turned off the anti-virus, added the program to the exceptions and even deleted it - no changes. What could causing the problem?

**Comment by mikeoverbay** [comment]
Make sure the path for res_mods is set correctly in Tank Eporter.
You should not need to extract anything to load a tank model. Just right click on the tank in the right panel and select "load this".
If you want to extract the tank to res_mods after its loaded, go to the top menu "Export/Extrtact" and select extract.

**Comment by Fortirus** [comment]
> 

Every time i run the programm it ask me to set path to the res_mods and i do it. 
And yes, i know how programm work, this is just a spesial case.

**Comment by mikeoverbay** [comment]
Are you sure you are setting the path correctly? It should not ask for the path every time it starts.
It should be like this for the current game version.
"C:\Games\World_of_Tanks\res_mods\1.15.0.2"
If this is correct and it isn't saving the path, try running TE in admin mode. It could be your system has strict security rules.

What special case? I might be able to solve this if I know what you are trying to do.

**Comment by Fortirus** [comment]
> It should be like this for the current game version.
> "C:\Games\World_of_Tanks\res_mods\1.15.0.2"

Oh, I just selected a "res_mods" folder, now when i choose the one with version it is stop asking for that.
But at last, it or running with admin mode didn't fix the error.

> What special case? I might be able to solve this if I know what you are trying to do.

To be honest, it's me who asked you about getting the textures of buildings in personal correspondence - you have already helped me a lot, so I didn’t want to bother you again through a letter. Besides, this problem may not only happen to me.

**Comment by mikeoverbay** [comment]
I made a video that shows how to export a building using PKG explorer, Loading it in to tank exporter, exporting the FBX, importing the FBX into 3DS max 2022 and setting up the textures for the church.
3DS Max 2009-2012 maybe later will create the textures for you when you load import the FBX.
Unit scale for both view and system in 3DS is 1 unit = 1cm. It is important to set this or navigation is very screwy.

Here is the link to the video.. It's not great. I get lost a few times but in the end.. it's works.
https://youtu.be/7urLdTKeLnA

**Comment by Fortirus** [comment]
> I made a video that shows how to export a building using PKG explorer, Loading it in to tank exporter, exporting the FBX, importing the FBX into 3DS max 2022 and setting up the textures for the church.

Wow, thank you, it did work! 
Post tests, turns out that the problem was that I was trying to open a primitive that was not in the "res_mods" subfolder.

**Comment by mikeoverbay** [comment]
Glad it's all sorted out!
You're welcome.
