### ISSUE TITLE
Normal Map Issue When Exporting

### ISSUE THREAD

**Issue by TheHarryAli** [mikeoverbay/TankExporter#48]
So when i try to export with textures and convert normal maps, some of the normal maps get converted correctly, but some of them becoming completely black.

**Comment by mikeoverbay** [comment]
The maps are already RGB maps? 
Which model? I'll have a look.

**Comment by mikeoverbay** [comment]
There may be a way to detect if alpha is used in the xml and if not, write 1.0 in to the alpha. Let me check on that when my heart slows down. I'm in the middle of a mild AFIB attack.

**Comment by mikeoverbay** [comment]
Yes.. I think I can detect if the red channel is used in the compressed normal map using the visual_processed xml.

**Comment by TheHarryAli** [comment]
I would appreciate it if you updated with that fix =)

**Comment by mikeoverbay** [comment]
OK.. This is fixed. Download version 121 and install it.
Please consider a small token of appreciation in the form of a donation.
