### ISSUE TITLE
export tank list

### ISSUE THREAD

**Issue by igorek247** [mikeoverbay/TankExporter#5]
new "export tank list" does not work. when you press yes it does nothing. i was hoping i can just extract all tanks

**Comment by mikeoverbay** [comment]
"Export Tank List" was feature was for use with Terra.. A program I wrote to view the maps from World of Tanks.
It only exported the tanks that had been selected and it exported them in a custom, packed format that could be read in very fast by Terra. 
I removed (Actually I hid) the menu items as Terra no long works with the new Encore game engine.
Too much data has changed to make it worth spending months figuring it all out again.
Hope that helps :)
