### ISSUE TITLE
Export Tracks instead of "rubber band"

### ISSUE THREAD

**Issue by flagmaggot** [mikeoverbay/TankExporter#50]
Doubt this is an error and is working as intended but is there a method to export the tank with the tracks populated or is this by design where it exports a rubber band placeholder?

**Comment by mikeoverbay** [comment]
I spent a month trying to figure out how to export the actual tracks and not the rubber band versions.
I could never figure out how to align them with the drive wheels or the correct spacing. A month and no success. Sorry

**Comment by flagmaggot** [comment]
No worries. It looks frustrating. I'll spend a little time to see what is possible.
