### ISSUE TITLE
Exporting with a style?

### ISSUE THREAD

**Issue by browntown-13** [mikeoverbay/TankExporter#51]
Hey, I'm painting an IRL version of the Desert Rats Cromwell ([https://i.imgur.com/liWCMtX.jpg](url)) and wanted to export it as a model so I could view it while painting, but I'm not sure how/if I can bring up the camouflage scheme, as the tank specific one (desert rats) does not show up under camouflages, neither do the general styles, e.g. Ad Astra, Black Widow, Christmas camos, etc.

Can this be loaded? It'd be a great help to me if there was a way to do it.

Thanks!

**Comment by mikeoverbay** [comment]
If this is a special tank, it should show up in the selection to load window as a skin.
If a camo is selected and visible on the tank, when you export the FBX,  it will mix the camo in to the albedo map. *_a,png
I hope this helps.

**Comment by browntown-13** [comment]
It is not a special tank, it is a 2D style for the regular Cromwell. Nothing shows up in the load menu either as its own tank, in loading for the Cromwell, or in the camouflages.

**Comment by mikeoverbay** [comment]
Try flushing the temp folder for Tank Exporter.
Go to File/Settings then down to Clear Temp Folder. Click yes on the next screen and TE will rebuild all the data.
The Cromwell loads fine on my end. I don't know what you mean by 2D style.

**Comment by mikeoverbay** [comment]
I did some research. It appears to be a new camo type. I'll check in to it sometime.

**Comment by browntown-13** [comment]
Thank you!
