### ISSUE TITLE
Spikes and weirdness when loading textures

### ISSUE THREAD

**Issue by Luna-wolf** [mikeoverbay/TankExporter#52]
Whenever I load a tank with textures shown, it explodes into a rendering mess of spikes and edges that fly around the place. 
![image](https://user-images.githubusercontent.com/47584772/155440465-557521cd-8301-4732-9875-b2efaf99a946.png)
![image](https://user-images.githubusercontent.com/47584772/155440490-274cd970-688b-488f-a56c-0b8e540b0050.png)

**Comment by mikeoverbay** [comment]
Oh my.. That isn't good. What video card?

As far as the FBX.. You can get a converter to update the FBX so apps that need a new version can read it.
https://www.autodesk.com/developer-network/platform-technologies/fbx-converter-archives
