### ISSUE TITLE
Feature request?

### ISSUE THREAD

**Issue by GabrielDja** [mikeoverbay/TankExporter#54]
Hello, your software is great!

But is it possible to make a 2nd version of the software compatible with **World of Tanks Blitz**?
To open models for example: .sc2 and .scg?
If it is possible, of course (:

Thanks for reading :D

**Comment by mikeoverbay** [comment]
Thank you.. I work hard on this software.

As far as opening the other models, I'd need to see a few of the model files. 
If you can post them some place where I can get ahold of them, I'll have a look.

**Comment by mikeoverbay** [comment]
I looked at both of those files using a hex editor and both are HTML data but Chrome wont read it because of errors>
Is there any files with .primitive , .model or .visual?

**Comment by GabrielDja** [comment]
No, there are only .sc2 and .scg files (Is it possible to decrypt these 2 files in .obj or .fbx?)

**Comment by mikeoverbay** [comment]
There is no geo data in them. Only HTML text and some links. Are the compressed data files?

**Comment by GabrielDja** [comment]
HTML, I don't think so but the main files are in .dvpl a special file...

**Comment by GabrielDja** [comment]
Ha I just found some .yaml files? Is it HTML?

**Comment by mikeoverbay** [comment]
usually they are config files. It should be loadable in notepad

**Comment by GabrielDja** [comment]
So there is no way to convert/open these files to .obj or .fbx?

**Comment by mikeoverbay** [comment]
No... no model data

**Comment by GabrielDja** [comment]
Okay
