### ISSUE TITLE
Can't connect Wot Api Server 

### ISSUE THREAD

**Issue by LQHHeorung** [mikeoverbay/TankExporter#56]
![Cant](https://user-images.githubusercontent.com/67264512/163677330-ad366c26-9f62-4fe9-bb4d-0fad09bb0171.JPG)

**Comment by Xmenas** [comment]
Same Error. .NET 4.8, Win10 x64. @mikeoverbay  Any ideas?

**Comment by ml37** [comment]
I  have same error.

**Comment by mikeoverbay** [comment]
Fixed!
Install latest version.
Thanks for pointing this out.
