### ISSUE TITLE
Issue when loading G16_PzVIB_TIGER_II

### ISSUE THREAD

**Issue by jaguar42l** [mikeoverbay/TankExporter#57]
Hello,

I can't load this tank, here is the error:
![image](https://user-images.githubusercontent.com/83211809/172045158-4c9ee31c-4762-4fba-ae72-7b715c0f6f12.png)
Regards

**Comment by mikeoverbay** [comment]
Fixed. Get version 124.
I had to allocate more space for turret types.
Thanks for the heads up :)

**Comment by jaguar42l** [comment]
> Fixed. Get version 124. I had to allocate more space for turret types. Thanks for the heads up :)

It's working fine, thanks
