### ISSUE TITLE
Can't creating Nodes by tier (08)

### ISSUE THREAD

**Issue by prame955** [mikeoverbay/TankExporter#59]
![Screenshot 2022-08-17 213736](https://user-images.githubusercontent.com/111444231/185165470-452b3c2d-011e-4efb-9b69-f56061b26c35.png)

**Comment by prame955** [comment]
I try to reinstall the latest version but nothing has changed. Please Help  @mikeoverbay  T T

**Comment by mikeoverbay** [comment]
Find and delete the wot_temp folder in your temp directory and restart tank exporter.
Let me know if this fixes it.

**Comment by prame955** [comment]
no, it's still the same.

**Comment by mikeoverbay** [comment]
Its working fine here.  I'm at a loss when I can't duplicate the issue.
Maybe make sure its set to NA region.

**Comment by prame955** [comment]
How? I'm in Asia region.

**Comment by mikeoverbay** [comment]
did you sort it out?

**Comment by prame955** [comment]
Sorry for not replying sooner. But it's fixed. I don't know how to fix it. But it's fixed. I think it's probably the version of the game. Anyway, thanks for your help.
