### ISSUE TITLE
Error when importing a model

### ISSUE THREAD

**Issue by SigmaTel71** [mikeoverbay/TankExporter#6]
``System.ArgumentException: Coloumn "gun_camouflage" does not belong to table gun.
   in System.Data.DataRow.GetDataColumn(String columnName)
   in System.Data.DataRow.get_Item(String columnName)
   in System.Data.DataRowExtensions.Field[T](DataRow row, String columnName)
   in Tank_Exporter.frmMain._Lambda$__20(DataRow row)
   in System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   in System.Linq.Enumerable.<DistinctIterator>d__64`1.MoveNext()
   in Tank_Exporter.frmMain.process_tank(Boolean save_tank)
   in Tank_Exporter.frmMain.m_load_Click(Object sender, EventArgs e)
   in System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   in System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   in System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   in System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   in System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   in System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   in System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   in System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   in System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   in System.Windows.Forms.ToolStrip.WndProc(Message& m)
   in System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)``

**Comment by mikeoverbay** [comment]
Is this the new 1.2 version thats about to hit NA?
If it is, I am aware of this and will be fixing it ASAP.
If this is version 1.1.x.x, which tank is this?

**Comment by SigmaTel71** [comment]
@mikeoverbay , no, this issue in on 1.2.0 from RU region. But I think it affects all regions who received the new patch.

**Comment by mikeoverbay** [comment]
Ok.. Thanks.. .
The 1.2.x.x is hitting here today... As soon as I get the update installed, I'll work on getting TE up and running again.

**Comment by SigmaTel71** [comment]
Great! Waiting for an update of TankExporter.😏

**Comment by mikeoverbay** [comment]
Version 69 is out.. This fixes the problem with client 1.2.0.0.
Thanks for letting me know it was broken!
