### ISSUE TITLE
Bug when loading tier 8 tanks

### ISSUE THREAD

**Issue by jaguar42l** [mikeoverbay/TankExporter#60]
Hello,
I"ve got this message when loading tier 8 tanks:
![image](https://user-images.githubusercontent.com/83211809/188305886-ef609bdb-4848-41de-9ee0-1cdde20ca6ab.png)
and strange black zones
Best regards

**Comment by FrancoisAR** [comment]
Having the same issue. Only one or two tanks actually load, the rest are  missing their tracks/hulls/turrets or not loading at all. Updated to the latest version as well and same thing after some tinkering. Also getting a problem compiling latest as it says BadImageFormatException: Could not load file or assembly 'SlimDX, Version=2.0.13.43, Culture=neutral, though it is there, same as for prev version

**Comment by SirHaxe** [comment]
same with tier 9. Strv K for example does not load at all and results in the following error:
`System.NullReferenceException: The object reference was not set to an object instance.
   at Tank_Exporter.frmMain.validate_path(String name)
   at Tank_Exporter.frmMain.process_tank(Boolean save_tank)
   at Tank_Exporter.frmMain.m_load_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

`************** Loaded Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4515.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll.
----------------------------------------
!_Tank Exporter
    Assembly-Version: 1.0.0.125.
    Win32-Version: 1.0.0.125.
    CodeBase: file:///Z:/TankExporter/!_Tank%20Exporter.exe.
----------------------------------------
Microsoft.VisualBasic
    Assembly-Version: 10.0.0.0.
    Win32-Version: 14.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4550.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4536.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4390.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4190.0 built by: NET48REL1LAST_B.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4566.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
System.Runtime.Remoting
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll.
----------------------------------------
SlimDX
    Assembly-Version: 2.0.13.43.
    Win32-Version: .
    CodeBase: file:///Z:/TankExporter/SlimDX.DLL.
----------------------------------------
Ionic.Zip
    Assembly-Version: 1.9.1.8.
    Win32-Version: 1.9.1.8.
    CodeBase: file:///Z:/TankExporter/Ionic.Zip.DLL.
----------------------------------------
System.Data
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4536.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll.
----------------------------------------
FbxSDK
    Assembly-Version: 1.0.4593.24947.
    Win32-Version: .
    CodeBase: file:///Z:/TankExporter/FbxSDK.DLL.
----------------------------------------
cttools
    Assembly-Version: 1.0.4723.22902.
    Win32-Version: .
    CodeBase: file:///Z:/TankExporter/cttools.DLL.
----------------------------------------
msvcm90
    Assembly-Version: 9.0.30729.9625.
    Win32-Version: 9.00.30729.9625.
    CodeBase: file:///C:/WINDOWS/WinSxS/x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9625_none_508ef7e4bcbbe589/msvcm90.dll.
----------------------------------------
Tao.DevIl
    Assembly-Version: 1.6.8.3.
    Win32-Version: 1.6.8.3.
    CodeBase: file:///Z:/TankExporter/Tao.DevIl.DLL.
----------------------------------------
Tao.OpenGl
    Assembly-Version: 2.1.0.12.
    Win32-Version: 2.1.0.12.
    CodeBase: file:///Z:/TankExporter/Tao.OpenGl.DLL.
----------------------------------------
Tao.Platform.Windows
    Assembly-Version: 1.0.0.5.
    Win32-Version: 1.0.0.5.
    CodeBase: file:///Z:/TankExporter/Tao.Platform.Windows.DLL.
----------------------------------------
Tao.FreeGlut
    Assembly-Version: 2.4.0.2.
    Win32-Version: 2.4.0.2.
    CodeBase: file:///Z:/TankExporter/Tao.FreeGlut.DLL.
----------------------------------------
System.Xml.Linq
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll.
----------------------------------------
System.Numerics
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll.
----------------------------------------
System.Data.DataSetExtensions
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.DataSetExtensions/v4.0_4.0.0.0__b77a5c561934e089/System.Data.DataSetExtensions.dll.
----------------------------------------
FastColoredTextBox
    Assembly-Version: 2.16.21.0.
    Win32-Version: 2.16.21.0.
    CodeBase: file:///Z:/TankExporter/FastColoredTextBox.DLL.
----------------------------------------
Accessibility
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll.
----------------------------------------
mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
----------------------------------------`

**Comment by alexfoo-productions** [comment]
Seeing similar issue trying to load IS-3

![{07AB347F-E35D-43F9-9651-646750E4B5FE}](https://user-images.githubusercontent.com/1757157/204141852-be88d1a5-9a54-4db8-9500-b6fea935b66d.png)

**Comment by mikeoverbay** [comment]
Look for version 127 guys; This should fix it.
Sorry for the delay.. Im 67. lol

**Comment by AlexG7796** [comment]
> Look for version 127 guys; This should fix it. Sorry for the delay.. Im 67. lol

1) I'm on version 127 and today application started to throw this exception on Tier 8. I tried to delete wot_temp and tried to reinstall it.
2) you are awesome, because you did this wonderful tool. I'm scale modeller and I can't say how much it is handy for me.
3) you are awesome, because you did this tool at 63(or something close to that).

**Comment by mikeoverbay** [comment]
https://github.com/mikeoverbay/TankExporter/blob/master/TankExporter_129.msi
