### ISSUE TITLE
Tanks not exporting to res_mods

### ISSUE THREAD

**Issue by LobodPl** [mikeoverbay/TankExporter#63]
After edditing .FBX file I have tried to unpack data to res_mods directory but nothing happens. 
Only by checking camouflages i was able to make some directory tree inside of res_mods.

**Comment by mikeoverbay** [comment]
Checked. Works fine here.
Make sure you have set the path to res_mods where it can be accessed. If it still won't work. It could be user rights. Try running TE in administer mode.

**Comment by mikeoverbay** [comment]
https://github.com/mikeoverbay/TankExporter/blob/master/TankExporter_129.msi
