### ISSUE TITLE
Another one connecting to WoT API issue

### ISSUE THREAD

**Issue by Siberian-Snake** [mikeoverbay/TankExporter#64]
If it's mass problem, can you please update the app so the API connection trouble won't show up again?

**Comment by mikeoverbay** [comment]
What mass problem?
Maybe its a key issue. Not likely but I'll check it.
I have no issues connecting. Maybe its something on their end.
Try flushing DNS?
https://grok.lsu.edu/article.aspx?articleid=19328

**Comment by dr3364895** [comment]
same with you ,can't connect to api server

**Comment by mikeoverbay** [comment]
Is this resolved?
