### ISSUE TITLE
Loading tire 10 Chatillon Char 25T failed

### ISSUE THREAD

**Issue by dr3364895** [mikeoverbay/TankExporter#65]
Hi
I don't why I can't loading this tank,I try clear temp folder ,reload api server ,clear mod folder,
error message is

System.NullReferenceException: Object reference not set to an instance of an object。
    Tank_Exporter.frmMain.validate_path(String name)
    Tank_Exporter.frmMain.process_tank(Boolean save_tank)
    Tank_Exporter.frmMain.m_load_crashed_Click(Object sender, EventArgs e)
    System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
    System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
    System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
    System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
    System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
    System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
    System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
    System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
    System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
    System.Windows.Forms.Control.WndProc(Message& m)
    System.Windows.Forms.ScrollableControl.WndProc(Message& m)
    System.Windows.Forms.ToolStrip.WndProc(Message& m)
    System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
    System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
    System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
    System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by QinSparrow** [comment]
same matter, wanna know why

**Comment by mikeoverbay** [comment]
Try this version. 

https://github.com/mikeoverbay/TankExporter/blob/master/TankExporter_129.msi

**Comment by mikeoverbay** [comment]
this is probably fixed.
