### ISSUE TITLE
not able to browse to res_mod folder

### ISSUE THREAD

**Issue by jaguar42l** [mikeoverbay/TankExporter#66]
Hello,

When executing tanks exporter, I can't browse to res_mod folder, opened windows is sticking to desktop
![image](https://user-images.githubusercontent.com/83211809/209332134-5b60e2fd-5b4f-4fc5-a50c-601e4fe5e10f.png)

Best regards

**Comment by mikeoverbay** [comment]
is the path set correctly?

**Comment by jaguar42l** [comment]
Problem is that I can't browse to any path from this window, it shows only the desktop

**Comment by jaguar42l** [comment]
I'am using Windows 11

**Comment by mikeoverbay** [comment]
Try running TE as admin
