### ISSUE TITLE
Failed to load shader

### ISSUE THREAD

**Issue by Skrollz3d** [mikeoverbay/TankExporter#67]
I've been having this error for 3 days and I can't find a solution when loading all the nodes of the tiers I get this warning
![Screenshot_4](https://user-images.githubusercontent.com/116226366/209581527-fef9b8f7-7d2f-4d0c-9a2d-7d10c0b45ddd.png)
![Screenshot_5](https://user-images.githubusercontent.com/116226366/209581537-b57a7cf8-98b4-4070-8463-0eb1b44022e7.png)

**Comment by mikeoverbay** [comment]
What Video hardware are you using?

**Comment by Skrollz3d** [comment]
RX 6750 XT bro with Ryzen 9 5950x

**Comment by mikeoverbay** [comment]
AMD cards have OpenGL issues. This is a forever bug AMD ignores.
