### ISSUE TITLE
can't open program

### ISSUE THREAD

**Issue by Mes103** [mikeoverbay/TankExporter#68]
I can't turn on the app because of a strange microsoft.NET error

**Comment by mikeoverbay** [comment]
What error?

**Comment by Mes103** [comment]
Sorry for that long waiting but im pasting here the things that shows up
when im starting the application:
(im from Poland so there are thing in polish language)


Szczegółowe informacje na temat wywoływania debugowania w trybie JIT (just
in time)
zamiast tego okna dialogowego znajdują się na końcu tego komunikatu.

************** Tekst wyjątku **************
System.ArgumentException: Niedozwolone znaki w ścieżce.
   w System.IO.Path.CheckInvalidPathChars(String path, Boolean
checkAdditional)
   w System.IO.Path.GetFileName(String path)
   w Tank_Exporter.frmMain.frmMain_Load(Object sender, EventArgs e)
   w System.EventHandler.Invoke(Object sender, EventArgs e)
   w System.Windows.Forms.Form.OnLoad(EventArgs e)
   w System.Windows.Forms.Form.OnCreateControl()
   w System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   w System.Windows.Forms.Control.CreateControl()
   w System.Windows.Forms.Control.WmShowWindow(Message& m)
   w System.Windows.Forms.Control.WndProc(Message& m)
   w System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   w System.Windows.Forms.ContainerControl.WndProc(Message& m)
   w System.Windows.Forms.Form.WmShowWindow(Message& m)
   w System.Windows.Forms.Form.WndProc(Message& m)
   w System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   w System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   w System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg,
IntPtr wparam, IntPtr lparam)


************** Zestawy załadowane **************
mscorlib
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.9139.0 built by: NET481REL1LAST_B
    CodeBase:
file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
!_Tank Exporter
    Wersja zestawu: 1.0.0.127
    Wersja Win32: 1.0.0.127
    CodeBase: file:///E:/!_Tank%20Exporter.exe
----------------------------------------
Microsoft.VisualBasic
    Wersja zestawu: 10.0.0.0
    Wersja Win32: 14.8.9032.0 built by: NET481REL1
    CodeBase:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Windows.Forms
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.9075.0 built by: NET481REL1LAST_C
    CodeBase:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.9139.0 built by: NET481REL1LAST_B
    CodeBase:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.9139.0 built by: NET481REL1LAST_B
    CodeBase:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Runtime.Remoting
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
SlimDX
    Wersja zestawu: 2.0.13.43
    Wersja Win32:
    CodeBase: file:///E:/SlimDX.DLL
----------------------------------------
Ionic.Zip
    Wersja zestawu: 1.9.1.8
    Wersja Win32: 1.9.1.8
    CodeBase: file:///E:/Ionic.Zip.DLL
----------------------------------------
System.Data
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.9110.0 built by: NET481REL1LAST_B
    CodeBase:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
FbxSDK
    Wersja zestawu: 1.0.4593.24947
    Wersja Win32:
    CodeBase: file:///E:/FbxSDK.DLL
----------------------------------------
cttools
    Wersja zestawu: 1.0.4723.22902
    Wersja Win32:
    CodeBase: file:///E:/cttools.DLL
----------------------------------------
msvcm90
    Wersja zestawu: 9.0.30729.9635
    Wersja Win32: 9.00.30729.9635
    CodeBase:
file:///C:/WINDOWS/WinSxS/x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9635_none_508ff82ebcbafee0/msvcm90.dll
----------------------------------------
Tao.DevIl
    Wersja zestawu: 1.6.8.3
    Wersja Win32: 1.6.8.3
    CodeBase: file:///E:/Tao.DevIl.DLL
----------------------------------------
Tao.OpenGl
    Wersja zestawu: 2.1.0.12
    Wersja Win32: 2.1.0.12
    CodeBase: file:///E:/Tao.OpenGl.DLL
----------------------------------------
Tao.Platform.Windows
    Wersja zestawu: 1.0.0.5
    Wersja Win32: 1.0.0.5
    CodeBase: file:///E:/Tao.Platform.Windows.DLL
----------------------------------------
Tao.FreeGlut
    Wersja zestawu: 2.4.0.2
    Wersja Win32: 2.4.0.2
    CodeBase: file:///E:/Tao.FreeGlut.DLL
----------------------------------------
mscorlib.resources
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_pl_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_pl_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** Debugowanie w trybie JIT **************
Aby włączyć debugowanie w trybie just in time (JIT), plik .config tej
aplikacji lub komputera (machine.config) musi mieć
wartość jitDebugging ustawioną w sekcji system.windows.forms.
Aplikacja musi być również skompilowana z włączonym
debugowaniem.

Na przykład:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Gdy debugowanie JIT jest włączone, wszystkie nieobsługiwane wyjątki
są wysyłane do debugera JIT zarejestrowanego na komputerze
i nie są obsługiwane w tym oknie dialogowym.

śr., 28 gru 2022 o 18:36 Coffee_ ***@***.***> napisał(a):

**Comment by mikeoverbay** [comment]
Try the new version?
https://github.com/mikeoverbay/TankExporter/blob/master/TankExporter_129.msi
