### ISSUE TITLE
wheeled tanks

### ISSUE THREAD

**Issue by Edrard** [mikeoverbay/TankExporter#7]
Good day
In attachment xml and model folder of EBR 75 this will help prepear for wheeled tanks
Still hope, one day we can use TankExporter for Supertest client and its not use WG API like main tank list.

[EBR_75.zip](https://github.com/mikeoverbay/TankExporter/files/2465549/EBR_75.zip)

Edrard from wot-news.com

**Comment by jlspeeddragon** [comment]
Nice to meet youEdrard from wot-news..

 I am JL dragon from the NA WoT forums that has been making the recent wheeled tanks  using the tank exporter that Mike has been working on ...  When I get a chance to get home download the WG updates for 1.2 ,  I will take a look at that file as well to see what has been changed...

**Comment by mikeoverbay** [comment]
I'll take a look at the visuals files in this.
Thanks for posting it.
TE uses the API to get information that is buried in other files.. Its easier than having to read every single tank xml file to get this info.. and a lot faster.

**Comment by Edrard** [comment]
Is it possible to integrate - https://github.com/hedger/BWXML
He unpack XMLs very fast. 
Becouse right now I need to swap tanks XML to open new tanks from SuperTest =(

**Comment by mikeoverbay** [comment]
I have a tool I wrote for XMLs.. Its in my main github page.
This looks like it will be easy to add to TE.. nothing real serious.. just one more layer of models and the locations are stored in the chassis visual file for each wheel.
Are these going to be in the game soon?

**Comment by Edrard** [comment]
Wheeled tank? I think yeah, in next 1-2 patches.

**Comment by mikeoverbay** [comment]
It will take a bit a coding but its not horrible to add make TE work with them.
The transform stack is the same.. just gotta add code to load the wheels
I'll do this once the wheeled tanks are in the actual game and not just the test server.
![f106](https://user-images.githubusercontent.com/15058778/46765274-96213500-ccac-11e8-9715-6a12b424d6a4.png)

**Comment by mikeoverbay** [comment]
Closing this as TE now loads and export these wheeled tanks.
