### ISSUE TITLE
OpenGL Shader Tank Fragment Crash

### ISSUE THREAD

**Issue by TIAGoXGaMeR13** [mikeoverbay/TankExporter#73]
i am having a problem with the shaders and openGL it keeps crashing the tank exporter when it finish loading all stuff @mikeoverbay 

![image](https://user-images.githubusercontent.com/101216698/218334507-058ca6e2-dcad-4c06-a9c6-cb16c1a8956e.png)

**Comment by mikeoverbay** [comment]
Try this..
Once tank exporter starts, ignore the errors.
Press F9
On the bottom where it says select shader, pick tank_shader.
Select the Fragment Program tap.
Find line 105 and remove the semicolon on the end. Normally, it's ignore.
Click Compile on the bottom right.
Let me know it it complies. If not, post any new errors

**Comment by TIAGoXGaMeR13** [comment]
the problem is i cant ignore the error, it keeps other stuff locked and when i press "ok" it crashes i pressed F9 nothing helped at all idk whats happening, this Error happens after the "Sorting Nodes" Finish then the OpenGL Issue error dont let me do anything at all. The tank exporter Starts just loading the nodes and i cant press any button. Well i will probably try reinstall wot but i reinstalled Tank Exporter alot of times and it is still happening. Is there a way i can Delete it completely? it instantly remembers the game path and res mods when i download it back.

**Comment by TIAGoXGaMeR13** [comment]
i will reinstall my World of tanks then i will comment here later if i succeed

**Comment by TIAGoXGaMeR13** [comment]
nothing seems to help @mikeoverbay i reinstalled it and it stills with this problem

**Comment by mikeoverbay** [comment]
Sorry.. find and delete the folder /temp/wot_temp

It should be this : C:\Users\USERNAME\AppData\Local\Temp\wot_temp
You need to enable access to this folder probably.

**Comment by Skrollz3d** [comment]
I have de same problem
![image](https://user-images.githubusercontent.com/116226366/219470883-91fca76f-0d92-4189-b33f-695ddb3e843b.png)

**Comment by Skrollz3d** [comment]
I was able to access with F9 after what do I do?
![image](https://user-images.githubusercontent.com/116226366/219474669-1f08c348-0b16-4fa3-87e1-480c85bd4afb.png)

**Comment by TIAGoXGaMeR13** [comment]
idk i dont have the acess for F9 it locks me. btw my video Card is: Radeon RX 580 PowerColor

**Comment by TIAGoXGaMeR13** [comment]
> Try this.. Once tank exporter starts, ignore the errors. Press F9 On the bottom where it says select shader, pick tank_shader. Select the Fragment Program tap. Find line 105 and remove the semicolon on the end. Normally, it's ignore. Click Compile on the bottom right. Let me know it it complies. If not, post any new errors

i did this, now i get no error messages but when it loads all everything and try to start it it just crashes instead.

**Comment by TIAGoXGaMeR13** [comment]
> Sorry.. find and delete the folder /temp/wot_temp
> 
> It should be this : C:\Users\USERNAME\AppData\Local\Temp\wot_temp You need to enable access to this folder probably.

Please Mike, Update the Tank Exporter or something. i really need it well idk if the issue is my pc that is not supported or the tank exporter itself

**Comment by TIAGoXGaMeR13** [comment]
@mikeoverbay Anwser when you can.

**Comment by mikeoverbay** [comment]
Remove the semicolon at the end of #define. Click compile and see if that fixes it. Probably not. Sent from my iPhoneOn Feb 16, 2023, at 5:11 PM, TIAGoXGaMeR13 ***@***.***> wrote:﻿
idk i dont have the acess for F9 it locks me. btw my video Card is: Radeon RX 580 PowerColor

**Comment by mikeoverbay** [comment]
AMD cards have issues with OpenGL.. Its been there for ever and they won't fix it. Sorry.

**Comment by TIAGoXGaMeR13** [comment]
there is no other way?? i remember your older versions of tank exporter
worked for me, can i get these older version in any way?

Em sex., 31 de mar. de 2023 às 15:21, Coffee_ ***@***.***>
escreveu:
