### ISSUE TITLE
normal issue and hidden vehicles

### ISSUE THREAD

**Issue by QinSparrow** [mikeoverbay/TankExporter#76]
Hello, will the normal issue of the gun part of the crashed part be fixed in the future? It now looks exceptional. In addition, can hidden vehicles such as Nameless, Edelweiss, Steel Hunter and computer-operated P43T from Halloween events be exported later? Thank you very much

**Comment by mikeoverbay** [comment]
https://github.com/mikeoverbay/TankExporter/blob/master/TankExporter_129.msi
