### ISSUE TITLE
Sherman Firefly does not load

### ISSUE THREAD

**Issue by lancefoxcia** [mikeoverbay/TankExporter#8]
Hello, I am using the latest version of Tank exporter, and when loading the tier 6 sherman firefly. it crashes the program with this error.

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.IndexOutOfRangeException: Index was outside the bounds of the array.
>    at Tank_Exporter.ModTankLoader.build_primitive_data(Boolean _add)
>    at Tank_Exporter.frmMain.process_tank(Boolean save_tank)
>    at Tank_Exporter.frmMain.m_load_Click(Object sender, EventArgs e)
>    at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>    at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>    at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
>    at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
>    at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
>    at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>    at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
> ----------------------------------------
> !_Tank Exporter
>     Assembly Version: 1.0.0.82
>     Win32 Version: 1.0.0.82
>     CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/!_Tank%20Exporter.exe
> ----------------------------------------
> Microsoft.VisualBasic
>     Assembly Version: 10.0.0.0
>     Win32 Version: 14.7.3190.0 built by: NET472REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
> ----------------------------------------
> System
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3353.0 built by: NET472REL1LAST_B
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> System.Core
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> System.Configuration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Xml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> System.Runtime.Remoting
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
> ----------------------------------------
> SlimDX
>     Assembly Version: 2.0.13.43
>     Win32 Version: 
>     CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/SlimDX.DLL
> ----------------------------------------
> Ionic.Zip
>     Assembly Version: 1.9.1.8
>     Win32 Version: 1.9.1.8
>     CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/Ionic.Zip.DLL
> ----------------------------------------
> System.Data
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
> ----------------------------------------
> FbxSDK
>     Assembly Version: 1.0.4593.24947
>     Win32 Version: 
>     CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/FbxSDK.DLL
> ----------------------------------------
> cttools
>     Assembly Version: 1.0.4723.22902
>     Win32 Version: 
>     CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/cttools.DLL
> ----------------------------------------
> msvcm90
>     Assembly Version: 9.0.30729.9518
>     Win32 Version: 9.00.30729.9518
>     CodeBase: file:///C:/Windows/WinSxS/x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9518_none_508db366bcbd18c4/msvcm90.dll
> ----------------------------------------
> Tao.DevIl
>     Assembly Version: 1.6.8.3
>     Win32 Version: 1.6.8.3
>     CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/Tao.DevIl.DLL
> ----------------------------------------
> Tao.OpenGl
>     Assembly Version: 2.1.0.12
>     Win32 Version: 2.1.0.12
>     CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/Tao.OpenGl.DLL
> ----------------------------------------
> Tao.Platform.Windows
>     Assembly Version: 1.0.0.5
>     Win32 Version: 1.0.0.5
>     CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/Tao.Platform.Windows.DLL
> ----------------------------------------
> Tao.FreeGlut
>     Assembly Version: 2.4.0.2
>     Win32 Version: 2.4.0.2
>     CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/Tao.FreeGlut.DLL
> ----------------------------------------
> System.Xml.Linq
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
> ----------------------------------------
> System.Numerics
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
> ----------------------------------------
> System.Data.DataSetExtensions
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Data.DataSetExtensions/v4.0_4.0.0.0__b77a5c561934e089/System.Data.DataSetExtensions.dll
> ----------------------------------------
> FastColoredTextBox
>     Assembly Version: 2.16.21.0
>     Win32 Version: 2.16.21.0
>     CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/FastColoredTextBox.DLL
> ----------------------------------------
> Accessibility
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
> ----------------------------------------
> 
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.

**Comment by mikeoverbay** [comment]
There is indeed a issue with the GB19_sherman_firefly.
Let me find and fix this and I'll let you know when the next release is out.

**Comment by mikeoverbay** [comment]
I uploaded version 83. This fixes the issue.
Thanks for letting me know! With out input, I can't make Tank Exporter better.
