### ISSUE TITLE
Decals folder missing

### ISSUE THREAD

**Issue by jaguar42l** [mikeoverbay/TankExporter#80]
Hello,

I get this message continuously:
![image](https://user-images.githubusercontent.com/83211809/230769606-3ad901c3-9f5a-43e0-a831-ea3269f75947.png)
Even if I click on "yes" it's still poping an restarting.

Regards

**Comment by mikeoverbay** [comment]
yep. I screwed up.
Let me fix it

**Comment by mikeoverbay** [comment]
Fixed. Get version 132
