### ISSUE TITLE
i cant choose a location outside of desktop

### ISSUE THREAD

**Issue by Stromy08** [mikeoverbay/TankExporter#81]
Szczegółowe informacje na temat wywoływania debugowania w trybie JIT (just in time)
zamiast tego okna dialogowego znajdują się na końcu tego komunikatu.

************** Tekst wyjątku **************
System.IO.FileNotFoundException: Nie można odnaleźć pliku 'C:\Users\fajny\OneDrive\Pulpit\1.19.1.0\paths.xml'.
Nazwa pliku: 'C:\Users\fajny\OneDrive\Pulpit\1.19.1.0\paths.xml'
   w System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   w System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   w System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   w System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   w System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   w System.IO.File.ReadAllText(String path)
   w Tank_Exporter.frmMain.frmMain_Load(Object sender, EventArgs e)
   w System.EventHandler.Invoke(Object sender, EventArgs e)
   w System.Windows.Forms.Form.OnLoad(EventArgs e)
   w System.Windows.Forms.Form.OnCreateControl()
   w System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   w System.Windows.Forms.Control.CreateControl()
   w System.Windows.Forms.Control.WmShowWindow(Message& m)
   w System.Windows.Forms.Control.WndProc(Message& m)
   w System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   w System.Windows.Forms.Form.WmShowWindow(Message& m)
   w System.Windows.Forms.Form.WndProc(Message& m)
   w System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   w System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   w System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Zestawy załadowane **************
mscorlib
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.9139.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
!_Tank Exporter
    Wersja zestawu: 1.0.0.131
    Wersja Win32: 1.0.0.131
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/!_Tank%20Exporter.exe
----------------------------------------
Microsoft.VisualBasic
    Wersja zestawu: 10.0.0.0
    Wersja Win32: 14.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.9139.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.9139.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.9075.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Remoting
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
SlimDX
    Wersja zestawu: 2.0.13.43
    Wersja Win32: 
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/SlimDX.DLL
----------------------------------------
Ionic.Zip
    Wersja zestawu: 1.9.1.8
    Wersja Win32: 1.9.1.8
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/Ionic.Zip.DLL
----------------------------------------
System.Data
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.9110.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
FbxSDK
    Wersja zestawu: 1.0.4593.24947
    Wersja Win32: 
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/FbxSDK.DLL
----------------------------------------
cttools
    Wersja zestawu: 1.0.4723.22902
    Wersja Win32: 
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/cttools.DLL
----------------------------------------
msvcm90
    Wersja zestawu: 9.0.30729.9635
    Wersja Win32: 9.00.30729.9635
    CodeBase: file:///C:/Windows/WinSxS/x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9635_none_508ff82ebcbafee0/msvcm90.dll
----------------------------------------
Tao.DevIl
    Wersja zestawu: 1.6.8.3
    Wersja Win32: 1.6.8.3
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/Tao.DevIl.DLL
----------------------------------------
Tao.OpenGl
    Wersja zestawu: 2.1.0.12
    Wersja Win32: 2.1.0.12
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/Tao.OpenGl.DLL
----------------------------------------
Tao.Platform.Windows
    Wersja zestawu: 1.0.0.5
    Wersja Win32: 1.0.0.5
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/Tao.Platform.Windows.DLL
----------------------------------------
Tao.FreeGlut
    Wersja zestawu: 2.4.0.2
    Wersja Win32: 2.4.0.2
    CodeBase: file:///C:/Program%20Files%20(x86)/Coffee_/Tank%20Exporter/Tao.FreeGlut.DLL
----------------------------------------
mscorlib.resources
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_pl_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_pl_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** Debugowanie w trybie JIT **************
Aby włączyć debugowanie w trybie just in time (JIT), plik .config tej
aplikacji lub komputera (machine.config) musi mieć
wartość jitDebugging ustawioną w sekcji system.windows.forms.
Aplikacja musi być również skompilowana z włączonym
debugowaniem.

Na przykład:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Gdy debugowanie JIT jest włączone, wszystkie nieobsługiwane wyjątki
są wysyłane do debugera JIT zarejestrowanego na komputerze
i nie są obsługiwane w tym oknie dialogowym.

**Comment by Stromy08** [comment]
idk mabye use deepL or google translate cos some stuff is in polish

**Comment by mikeoverbay** [comment]
MAKE SURE YOU SET THE GAME PATH TO THE ROOT FOLDER OF THE GAME. NOT THE RES_MODS PATH.
RES_MODS PATH IS THE ONE THAT POINTS AT THE CURRENT VERSION IN RES_MODS;

**Comment by Stromy08** [comment]
it doesnt let me chose tha path and when i open it in setting i cant select any location outside of desktop

**Comment by mikeoverbay** [comment]
Path to the game folder should look like this or close depending on where the game is installed;
C:\Games\World_of_Tanks_NA

**Comment by mikeoverbay** [comment]
ok.. try running TE in admin mode

**Comment by mikeoverbay** [comment]
The path info is saved in wot_temp under your temp folder. You can manually edit it if all else fails

**Comment by Stromy08** [comment]
![Zrzut ekranu 2023-04-12 204808](https://user-images.githubusercontent.com/125371422/231569107-57980e26-a9a0-41ec-bb5f-2b4f64211ef9.png)

**Comment by Stromy08** [comment]
![Zrzut ekranu 2023-04-12 205201](https://user-images.githubusercontent.com/125371422/231569545-42a542bc-c5a7-4824-b31f-96faef0fc17a.png)
this temp folder?

**Comment by mikeoverbay** [comment]
game_Path.txt - game .. Should contain something like this : C:\Games\World_of_Tanks_NA
res_mods_Path.txt - res_mods .. same thing .. C:\Games\World_of_Tanks_NA\res_mods\1.20.0.1
You can create these if the do not exist

**Comment by mikeoverbay** [comment]
yes correct folder

**Comment by mikeoverbay** [comment]
[game_Path.txt](https://github.com/mikeoverbay/TankExporter/files/11215354/game_Path.txt)
[res_mods_Path.txt](https://github.com/mikeoverbay/TankExporter/files/11215355/res_mods_Path.txt)
Here are mine paths

**Comment by mikeoverbay** [comment]
get version 132.. 131 will probably crash on the decals

**Comment by Stromy08** [comment]
i cant choose the file i showed through temp but i pinned world of tanks to the quick access in file explorer and i think something happened

**Comment by Stromy08** [comment]
and it stopped when i started it up again it sais 
![image](https://user-images.githubusercontent.com/125371422/231570458-e3081e35-c1c7-48ec-870e-e31f5c31dbf0.png)

**Comment by Stromy08** [comment]
k, i think it works

**Comment by Stromy08** [comment]
![image](https://user-images.githubusercontent.com/125371422/231570727-da81524c-59be-4956-923d-9ac24a4e8706.png)

**Comment by mikeoverbay** [comment]
cool!

**Comment by Stromy08** [comment]
but after it sorts everything it just crashes

**Comment by Stromy08** [comment]
then it wants me to update the res mods path

**Comment by Stromy08** [comment]
so i do, it sorts and crashes

**Comment by mikeoverbay** [comment]
you need the decals and version 131 is broken

**Comment by Stromy08** [comment]
so i should use just a different version of tank exporter?

**Comment by mikeoverbay** [comment]
yes
i just updated it

**Comment by mikeoverbay** [comment]
https://github.com/mikeoverbay/TankExporter/raw/master/TankExporter_132.msi

**Comment by Stromy08** [comment]
i installed it but i im having the same issue

**Comment by mikeoverbay** [comment]
crash after sorting?

**Comment by Stromy08** [comment]
yeah after it does the thing

**Comment by Stromy08** [comment]
oh.. my 3080 is broken so im running amd 5600G i think
its integrated graphics

**Comment by mikeoverbay** [comment]
AMD?
AMD has been a issue with Tank Exporter

**Comment by Stromy08** [comment]
oh so i pobably wont run it without and nvidia gpu

**Comment by mikeoverbay** [comment]
Probably not. I just got my hands on a all in one Dell with AMD graphics so I am going to work on fixing this issue.

**Comment by mikeoverbay** [comment]
Sorry about your 3080. Nice cards and expensive

**Comment by Stromy08** [comment]
yeah, i am currently packing it up and ill ship it to get it fixed (again) 

anyway thanks for your time

**Comment by mikeoverbay** [comment]
I tired :)
let me know if it work when you get the card back.

**Comment by Stromy08** [comment]
i will :) thx

**Comment by mikeoverbay** [comment]
hey.. I uploaded a AMD compatibility test.
Try it and see if it works at all.

**Comment by Stromy08** [comment]
ill try it now

**Comment by Stromy08** [comment]
it works!

**Comment by Stromy08** [comment]
it dopesnt crash after sorting nodes but it does after loading in a tank i think

**Comment by mikeoverbay** [comment]
still crashing?
Any messages?

**Comment by Stromy08** [comment]
no, it just turn off

**Comment by mikeoverbay** [comment]
I'll get digging. Sorry man.

**Comment by Stromy08** [comment]
its ok, i thank you

**Comment by mikeoverbay** [comment]
Does this window open? Tying to narrow it down.
![sel_scr](https://user-images.githubusercontent.com/15058778/232070597-f1c6c5ce-bb59-44f8-b663-d8d38982f583.png)

**Comment by Stromy08** [comment]
it does after i press continue it shuts down

**Comment by mikeoverbay** [comment]
ok.. So it crashes somewhere when its loading the model.

**Comment by Stromy08** [comment]
yep, even when i tried to load just the turrest or something

**Comment by Stromy08** [comment]
![image](https://user-images.githubusercontent.com/125371422/232073594-5dc0a094-f923-40c8-9ed9-1f51dcb61ccc.png)
![image](https://user-images.githubusercontent.com/125371422/232073652-5f00f6af-9feb-4eb5-9e7d-3efa73b9a2cd.png)

**Comment by Stromy08** [comment]
then it crashes

**Comment by mikeoverbay** [comment]
Make sure to check one item for each tank part like in the image I sent. Chassis, Hull, Turret and gun.

**Comment by Stromy08** [comment]
when i did that too the same thing happened

**Comment by mikeoverbay** [comment]
let me create version to try and trap where this is going wrong.

**Comment by Stromy08** [comment]
ok thanks

**Comment by mikeoverbay** [comment]
uninstall 133 and try this one. It will have pop ups message boxes.
Let me know what the last one that pops up says (if any do).
http://tnmshouse.com/test

**Comment by mikeoverbay** [comment]
Work with me and I'll do my best to solve this.

**Comment by Stromy08** [comment]
im trying that version rn

**Comment by Stromy08** [comment]
after that it crashes

**Comment by mikeoverbay** [comment]
ok.. so its crashing loading the actual tank data.
Need to add more traps. Give me a few minutes.

**Comment by mikeoverbay** [comment]
Uninstall and try it again, OK?
http://tnmshouse.com/test

**Comment by mikeoverbay** [comment]
I just noticed the terrain has no decals on it. Did you check the box to disable loading them?
If so, there is a option under 'file/settings' to turn loading back on. If it slows your system way down, you can shut them off again. Just use the 'enable loading decals' option again.

**Comment by Stromy08** [comment]
> uninstall 133 and try this one. It will have pop up message boxes. Let me know what the last one that pops up says (if any do). http://tnmshouse.com/test

in this one when i enable decals it crashes also but after a bit more time so ill try the other version

**Comment by Stromy08** [comment]
it crashed after start making lists

**Comment by Stromy08** [comment]
![image](https://user-images.githubusercontent.com/125371422/232149716-35f75c5f-02bb-465d-bce4-ca7e65c51d90.png)

**Comment by mikeoverbay** [comment]
Progress!
Ok.. is a issue with the lists.

**Comment by mikeoverbay** [comment]
Try it again, please.
I took out the unneeded traps. 
http://tnmshouse.com/test

**Comment by Stromy08** [comment]
now it crashes again

**Comment by Stromy08** [comment]
and i noticed it even crashes when i press the x in the components selector screen

**Comment by Stromy08** [comment]
but not when i press cancel

**Comment by Stromy08** [comment]
oh, and it also crashes when i load up an fbx

**Comment by mikeoverbay** [comment]
ok.. I removed the traps. I was hoping it would create the display lists now. We know it makes to that point.
Loading a FBX also creates a list. It will only import the FBX files with the correct tank parts. It isn't a general FBX viewer.
I'll dig some more.

**Comment by mikeoverbay** [comment]
ok.. I added a bunch a traps around the creation of the lists.
Can you try it again?
http://tnmshouse.com/test

**Comment by Stromy08** [comment]
> ok.. I removed the traps. I was hoping it would create the display lists now. We know it makes it to that point. Loading a FBX also creates a list. It will only import the FBX files with the correct tank parts. It isn't a general FBX viewer. I'll dig some more.

i loaded a tank fbx

**Comment by Stromy08** [comment]
i get the 4 list popups, then i get them again and again adn again and again

**Comment by Stromy08** [comment]
and once it crashed and now the tank just didnt load at all

**Comment by mikeoverbay** [comment]
damn.. let me make sure I uploaded the program. That version was bad.

**Comment by Stromy08** [comment]
ok

**Comment by mikeoverbay** [comment]
ok.. sorry. Im trying lol
try it again.

**Comment by Stromy08** [comment]
k

**Comment by Stromy08** [comment]
im tryin git now

**Comment by mikeoverbay** [comment]
I don't get why it runs in the A9 chip and not on the 5600. I know AMD is very picky about errors.

**Comment by Stromy08** [comment]
it is wierd

**Comment by Stromy08** [comment]
it crashes without any of the debug windows showing up

**Comment by mikeoverbay** [comment]
ok
Lets try something else

**Comment by mikeoverbay** [comment]
its a pain but its the only way to sort it out.
http://tnmshouse.com/test

**Comment by Stromy08** [comment]
ik

**Comment by mikeoverbay** [comment]
This just checks to see if GL is throwing an error.

**Comment by Stromy08** [comment]
also i have a question...

do you know why those files are called that?
![image](https://user-images.githubusercontent.com/125371422/232246033-14e9d070-fd86-4ca0-b4a0-59f98a271b1f.png)

**Comment by mikeoverbay** [comment]
must of been having a bad day? I have a jump to location named that.

**Comment by Stromy08** [comment]
lmao

**Comment by mikeoverbay** [comment]
I just did a search for the entire project for 'fuckyou' and it doesn't exist. It must be inside of an external module.

**Comment by Stromy08** [comment]
its in cctool.dll

**Comment by Stromy08** [comment]
![image](https://user-images.githubusercontent.com/125371422/232246382-efb9306e-c38f-412a-99c0-db22d4e7a6f0.png)

**Comment by Stromy08** [comment]
and it still crashes

**Comment by mikeoverbay** [comment]
oh... yeah. Thats mine. It compresses float numbers in to WGs unit format

**Comment by Stromy08** [comment]
very descriptive name

**Comment by Stromy08** [comment]
and yeah, it crashes when loading a tank

**Comment by mikeoverbay** [comment]
[opengl Capabilities.zip](https://github.com/mikeoverbay/TankExporter/files/11240314/opengl.Capabilities.zip)
drag the folder on the desk top and run the program inside.
See if your driver supports lists.

**Comment by mikeoverbay** [comment]
you should see this
GL_MAX_LIST_NESTING

**Comment by Stromy08** [comment]
does it have to be on desktop?

**Comment by mikeoverbay** [comment]
no

**Comment by Stromy08** [comment]
so i run the exe
choose deafult
![image](https://user-images.githubusercontent.com/125371422/232247268-d3d33631-8703-4b36-a5b0-ffd760b06a9f.png)

**Comment by Stromy08** [comment]
and then what?

**Comment by mikeoverbay** [comment]
yeah

**Comment by mikeoverbay** [comment]
type list in the filter box

**Comment by Stromy08** [comment]
oh sheit

**Comment by Stromy08** [comment]
idk is **n/a** or or off?

**Comment by Stromy08** [comment]
![image](https://user-images.githubusercontent.com/125371422/232247340-a005d95e-bcac-4632-a390-03cf8337fdcd.png)

**Comment by mikeoverbay** [comment]
you get N/A in the lower window?

**Comment by mikeoverbay** [comment]
you get N/A in the lower window?

**Comment by Stromy08** [comment]
which lower window?

**Comment by Stromy08** [comment]
![image](https://user-images.githubusercontent.com/125371422/232247383-81fd13c1-b3b7-46a8-82b8-8e547e69f232.png)

**Comment by mikeoverbay** [comment]
oh no. OK.. we are going to have to find a driver that supports GL lists.

**Comment by Stromy08** [comment]
so it was my drivers

**Comment by mikeoverbay** [comment]
yep

**Comment by Stromy08** [comment]
ill try to fix those

**Comment by mikeoverbay** [comment]
who supplied the driver? AMD or PC builder or windows?

**Comment by Stromy08** [comment]
idk i dont remember, i remember having a ton of problems with my 3080 and doing stuff with drivers and re-installing them and stuff maby in interfeared with the amd ones

**Comment by mikeoverbay** [comment]
I would remove all of them including gl drivers. There is a tool for that. I'll find a link

**Comment by mikeoverbay** [comment]
https://www.guru3d.com/files-details/display-driver-uninstaller-download.html

**Comment by Stromy08** [comment]
i installed the driver now ill see if it works

**Comment by mikeoverbay** [comment]
create a restore point before running that tool just in case.

**Comment by Stromy08** [comment]
i used official amd drivers for now

**Comment by mikeoverbay** [comment]
you could re-run the capabilities test

**Comment by Stromy08** [comment]
i did with same result

**Comment by mikeoverbay** [comment]
Im looking for any info on this I can find

**Comment by mikeoverbay** [comment]
try it again.
If it crashes before drawing the terrain, it for sure isn't going to work with display list.

**Comment by Stromy08** [comment]
the terrain is working

**Comment by mikeoverbay** [comment]
ok.. so asking to OpenGL to gen a list id isn't crashing.
Now.. Lets find out if it actually is generating one.
Try it again when you get a chance. http://tnmshouse.com/test
A box  should pop up saying "List id =  ". If that number is greater than zero, its returning a valid list ID.
I'm sorry about all this but there isn't easy way to find the issue. We need to work through it.

**Comment by Stromy08** [comment]
dont apologise good sir, i should be thenking you for putting in the time and effort to help

**Comment by mikeoverbay** [comment]
let me know when you try out that new test.

**Comment by Stromy08** [comment]
sorry for the wait but here what i got:
![image](https://user-images.githubusercontent.com/125371422/232859528-1e76d1a7-2ab2-44fa-abc5-425601305862.png)
i got list id 6 and some error but i didnt even get a chance to load up a tank

**Comment by mikeoverbay** [comment]
Can you try it again?

**Comment by Stromy08** [comment]
![image](https://user-images.githubusercontent.com/125371422/233455405-265b65c2-e40d-48a1-9da8-ce4cb42b2f18.png)

**Comment by mikeoverbay** [comment]
That is the infamous Invalid Enum. It is causes when the GL doesn't recognize a enumerable command.
We are getting there :)

**Comment by mikeoverbay** [comment]
Ok.. I found an error. It does not like the gl_Smooth enum. This is only used in simple lighting and as far as I can tell, has no effect removing it as it still renders fine.
Try it again when you get a chance. http://tnmshouse.com/test

**Comment by Stromy08** [comment]
it aint work just crashes when loading model with no message

**Comment by Stromy08** [comment]
oh yeah, and btw somehow before i did manage to export a model with the program with my pc, but im not sure whether i was using my apu or the gpu back then but i have 2 tanks models on my pc from the game
![image](https://user-images.githubusercontent.com/125371422/233832463-7bc301bc-ccae-41ea-aeab-310d3d1fe372.png)

**Comment by Stromy08** [comment]
Idk if it still relevant but the newest version works on the AMD CPU without issues. thanks
