### ISSUE TITLE
tank model messed

### ISSUE THREAD

**Issue by jaguar42l** [mikeoverbay/TankExporter#82]
Hello,
When I export FBX here is what I've got in 3DSMAX and when reimporting in Tank exporter
![image](https://user-images.githubusercontent.com/83211809/232305548-c701a46f-fb72-417c-8be2-f30ef94c1782.png)
Regards

**Comment by mikeoverbay** [comment]
looks like you are losing all the transform information when you export from Max.
Select version 9 FBX when exporting from max.

**Comment by jaguar42l** [comment]
I think there is something weird with the FBX because if I export FBX and reimport it immediately in tank exporter I don't see anything

**Comment by mikeoverbay** [comment]
let me test that here

**Comment by mikeoverbay** [comment]
Yes.. Something is wrong.
I will find out and let you know when its fixed.

**Comment by mikeoverbay** [comment]
Fixed. download version 134

**Comment by jaguar42l** [comment]
It's working, thanks
