### ISSUE TITLE
Crashing when importing models

### ISSUE THREAD

**Issue by hydratioNx99** [mikeoverbay/TankExporter#83]
So I had this issue when trying to import modified tank models...
For example I edited the Kpz 50t by removing the camonets and thingy for the gun

Before: ![alt text](https://i.imgur.com/CymE0MZ.png "Before")
After: ![alt text](https://i.imgur.com/VNCox81.png "After")

Which results in a crash:
[Crashlog]: https://pastebin.com/112S41Zd
![alt text](https://i.imgur.com/j3K6n25.png "Crash")

But when I just edit part of the gun model for example, it does not crash:
![alt text](https://i.imgur.com/FU1ljU3.png "Kpz50tnoCrash")

I'm assuming that it crashes because it can't load the deleted models but it could be something different entirely...
Is there some workaround?

**Comment by mikeoverbay** [comment]
zip the FBX and let me look at it.

**Comment by hydratioNx99** [comment]
> zip the FBX and let me look at it.

sorry just saw it now

[Kpz 50 t2.zip](https://github.com/mikeoverbay/TankExporter/files/12250989/Kpz.50.t2.zip)

**Comment by mikeoverbay** [comment]
is this still broken?
