### ISSUE TITLE
FBX 2009 models not working in TankExporter

### ISSUE THREAD

**Issue by Ycam4uk** [mikeoverbay/TankExporter#85]
When loading an FBX model in TankExporter, an error occurs: An unhandled exception in the application. When you click Continue, the application will ignore the error and try to continue. When you click the "Exit" button, the application will exit immediately. The input string was not in the correct format.
Mike overbay, pleas help.

**Comment by mikeoverbay** [comment]
find the temp folder wot_temp under /appdata/temp and delete the folder.
Update to the new 136 version of tankexport and try that.
Also, you need net 4.8 installed.
https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48
