### ISSUE TITLE
Program not loading Data from Packages

### ISSUE THREAD

**Issue by 1stSavagerY** [mikeoverbay/TankExporter#86]
When I launch program, it get stucks on "Loading Data from Packages..." and I get an error saying "System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\******\AppData\Local\Temp\wot_temp\decalsdecals\maps\decals_pbs\00_CA_Decals'."

**Comment by jaguar42l** [comment]
Hello,
same issue !
Regards

**Comment by QinSparrow** [comment]
hello, the same issue! no idea what's wrong with that.

**Comment by mikeoverbay** [comment]
Sorry guys. I have been sick. Remember, I'm nearly 70?
What should work is to delete the wot_temp folder and run TE again so it recreates all folders.
It is located here :C:\Users\USENAME\AppData\Local\Temp\wot_temp.
What is happening is windows deletes the decal folder. I have no idea why but every few weeks, it vanishes.
You can shut of storage sense and windows will stop doing it but it also will not clean the temp folder ever of other unused trash. https://www.easeus.com/data-recovery/stop-windows-11-automatically-deleting-files.html#:~:text=Disable%20Storage%20Sense%20to%20Stop,11%20from%20automatically%20deleting%20files.

**Comment by 1stSavagerY** [comment]
I am still unfortunately getting the issue. I'm setting all the paths that the program is telling me to and I'm getting the same "could not find a part of the path" error.  Could it be that I'm setting the paths incorrectly? I can provide screenshots if needed :)

**Comment by mikeoverbay** [comment]
is WoT installed on C?

**Comment by QinSparrow** [comment]
my question has been fixed thanks mikeoverbay.

**Comment by mikeoverbay** [comment]
I found the bug and will be updating soon!
Thanks for the heads up!

**Comment by BKM-GitHub** [comment]
Thanks for the new version, mikeoverbay.
But this still gives me an error.

System.IO.DirectoryNotFoundException: Part of the path 'C:\Users\AppData\Local\Temp\wot_temp\decalsdecals\maps\decals_pbs\00_CA_Decals' was not found.

The path is firmly specified.
game_path → C:\Games\World_of_Tanks_NA
res_mods_path → C:\Games\World_of_Tanks_NA\res_mods

This error did not occur in ver134, it occurred from ver136. (I not tried ver135.)

**Comment by 1stSavagerY** [comment]
I tried the new version and am unfortunately getting the same error that BKM is getting

**Comment by mikeoverbay** [comment]
omg 
decalsdecals That is wrong.
Let me fix this.

**Comment by mikeoverbay** [comment]
ok.. Try version 138. Sorry guys.

**Comment by 1stSavagerY** [comment]
Good news and bad news.  The program is able to find the path correctly and the error no longer occurs.  However, it crashes any time I try and load any models.

**Comment by BKM-GitHub** [comment]
Thanks for the update, Mike Overbay.
All errors on my PC have been fixed :)

**Comment by BKM-GitHub** [comment]
Thanks for the update, mikeoverbay.
All errors on my PC have been fixed :)

**Comment by mikeoverbay** [comment]
Glad to hear this!
