### ISSUE TITLE
Textures are not added

### ISSUE THREAD

**Issue by Ycam4uk** [mikeoverbay/TankExporter#87]
![Screenshot](https://github.com/mikeoverbay/TankExporter/assets/136717722/0d8042bb-be47-4efb-b3e7-c4c6bfdda01d)
Unable to load textures.
Help

**Comment by mikeoverbay** [comment]
is this like this on all tanks?

**Comment by mikeoverbay** [comment]
even if you don't run the game in HD, it is a good id to have the HD PKG files. There could be that I have a bug that relies on the HD files but I haven't had any reports of this.

**Comment by mikeoverbay** [comment]
This is when you import a FBX?
Im really sorry im not getting back earlier. I got a shit load on my plate.

**Comment by mikeoverbay** [comment]
I Just did a update to 137..
https://github.com/mikeoverbay/TankExporter/blob/master/TankExporter_137.msi
Don't think it will fix your problem but it will fix other bugs.

**Comment by mikeoverbay** [comment]
close.. I dont know if this is fixed.
