### ISSUE TITLE
Compatibility with custom camo (BrandedTanks mod)

### ISSUE THREAD

**Issue by synopss** [mikeoverbay/TankExporter#88]
There is a mod used to show custom camos based on some patterns and other configuration : [https://gitlab.com/wot-public-mods/branded-tanks](url)

Is it possible to use TankExporter as a previewer for this mod ? It would avoid having to restart the whole game everytime we are trying to change any camo config from this mod.

**Comment by mikeoverbay** [comment]
if it is located in the res_mods path tree, it should load it when you load the tank. TE loads from the res_mods folder first and if it isn't there, it pulls it from the pkg files. It is actually a lot faster loading it from res_mods because of direct path and no pkg file searches.

**Comment by synopss** [comment]
Those are not regular skins. They are patterns stored into dds files who are being applied to tanks.
I tested with your mod without sucess hence my question.

I guess that's new feature idea :)
