### ISSUE TITLE
Tank exporter stops working after trying to load a few tank models.

### ISSUE THREAD

**Issue by PTLD93** [mikeoverbay/TankExporter#90]
My Tank exporter stops working when i try loading the T57 heavy and the Strv 103B at Tier 10,i dont know if it has to do with the game or the Tank exporter wasnt able to find the model or get the primitives from the games pkg files.

**Comment by mikeoverbay** [comment]
Work with the BUGs version of TE.
I am trying to get this to work again with AMD cards and after, I will address these other issues.
Sorry for the delay.

**Comment by PTLD93** [comment]
No worries,i also found another bug,the Maus thumbnail is different from the stock one,it shows that one maus with 2 cannons which i think its from the autocannons update,and the model cannot be loaded,as it also breaks the exporter the same way for the T57 heavy and Strv 103B.
