### ISSUE TITLE
Exporting FBX dont Export the 3d model just the textures

### ISSUE THREAD

**Issue by TIAGoXGaMeR13** [mikeoverbay/TankExporter#92]
Exporting FBX dont Export the 3d model just the textures. for some reason i dont know it only exports the texture and ignore the fbx file which is the thing i really want

**Comment by TIAGoXGaMeR13** [comment]
![image](https://github.com/mikeoverbay/TankExporter/assets/101216698/ab2ae870-b302-429e-98d6-706715c08bee)
 this is some error i get when i finnish the Tank Exporter Setup. if this has some relation can you reply me? @mikeoverbay

**Comment by TIAGoXGaMeR13** [comment]
please i need help with that

**Comment by TIAGoXGaMeR13** [comment]
and yes i reinstalled,repaired it and i deleted %temp% files but this still happens @mikeoverbay

**Comment by TIAGoXGaMeR13** [comment]
sadly every time i try to use this tool it just bugs. dude you should share all the other versions for the public too. dont just replace them cause some just work for some ppl while others dont. im using Nvidia Notebook RTX 3070 idk if it has problems with compatibility too. cause the last time i tried to use your tool i was on AMD PC

**Comment by mikeoverbay** [comment]
The deferred buffer bug is odd. It has something internal that I can't seem to find.
The app still runs fine once to ignore this.
If it is working after ignoring the message box, let me know and I'll just remove that trap.
In fact.. I'm just going to do that now
Get the BUGs version

**Comment by mikeoverbay** [comment]
Friendly reminder that I am old.. and this is becoming work that interferes with what time I have for my machine projects.
I am doing my best to try and maintain it tho it may be slow at times.
I spend many many hours figuring out how to manipulate the data so that the models can be opened and rendered.
I have been looking for someone to rewrite TE but its a huge amount of work no one wants to take on.

**Comment by mikeoverbay** [comment]
Follow and post in this bug report and lets combine efforts to improve the app.
https://github.com/mikeoverbay/TankExporter/issues/89

**Comment by NatetheGreaterest** [comment]
> Friendly reminder that I am old.. and this is becoming work that interferes with what time I have for my machine projects. I am doing my best to try and maintain it tho it may be slow at times. I spend many many hours figuring out how to manipulate the data so that the models can be opened and rendered. I have been looking for someone to rewrite TE but its a huge amount of work no one wants to take on.

What programming language is TE written in? Im young and have plenty of time t work on a project like that!

**Comment by mikeoverbay** [comment]
not sure where this is so I'm closing it.
