### ISSUE TITLE
Textures?

### ISSUE THREAD

**Issue by Sparton385** [mikeoverbay/TankExporter#93]
So i got almost everything to work, but the lighting of the textures is just entirely off, and i have no idea how to fix it. Got any ideas?
![image](https://github.com/mikeoverbay/TankExporter/assets/124919964/426179e5-5fa5-4c99-a9d1-048a70958636)

**Comment by Sparton385** [comment]
I will say it does seem to be reversed

**Comment by mikeoverbay** [comment]
looks like the normals are backwards on X.
I'll look in to this when I get some of the other issues fixed.

**Comment by Sparton385** [comment]
All good, I just didnt even knowwhere to start to fix it

**Comment by Sparton385** [comment]
![image](https://github.com/mikeoverbay/TankExporter/assets/124919964/42fe5612-996f-4545-9540-dbacf236de8c)
![image](https://github.com/mikeoverbay/TankExporter/assets/124919964/051a353a-e677-404f-b67f-296eba8bc40f)

I just want to see if this helps some more, as like i said I have no idea what to do to fix it. I tried to flip the textures by using paint net, bucket painting and using color clearer to "flip" it but it doesnt necessarily work

**Comment by mikeoverbay** [comment]
Is this a stock model? I don't play anymore, I just try and keep up with the changes that keep breaking parts of TE.

**Comment by Sparton385** [comment]
You are good, all the parts on the tank are from 3d styles that i placed via blender, i suppose that is stock? idk, but i tried to fix the issue by flipping the .AO color in paint.net which fixed the issue for some but doesnt fix others. It may be just an issue with my pc but i just have no idea
