### ISSUE TITLE
when loading into blender, some oscillating turrets load inverted and sometimes backwards

### ISSUE THREAD

**Issue by Dragonflable75** [mikeoverbay/TankExporter#94]
hello, while exporting the lorraine 40t into blender, i noticed that the gun (upper turret) loaded backwards. you can see it next to the somua sm as the turret is almost identical, i just made a floor and edited the lighting for render purposes
![lorr 40t(right) and somua sm(left)](https://github.com/mikeoverbay/TankExporter/assets/75908765/f16c7d62-787f-449e-8255-81107d3a0c5f)

 Not thinking much of it, i just flipped it 180 degrees and moved on. However, when i tried to modify the turret, i noticed it was mirrored horizontally, but strangely everything else wasn't. this was also the case with the somua sm. you can see on the right side of the hull that the rolled up metal tether is untouched, however you can tell the turret is inverted by the roof machine gun and the one mounted next to the gun.

![inverted turret](https://github.com/mikeoverbay/TankExporter/assets/75908765/6bc9797b-3b92-41eb-8f61-df1e161c3eb7)

i could easily fix this issue in blender, but the issue would come when importing the result into tank exporter, i don't know what to do to make it work correctly.

thank you for your time
Dragonflable75

**Comment by mikeoverbay** [comment]
This is a matrix issue with skinned models.
Try setting the material to 2 sided. 
Let e know if it helps.
