### ISSUE TITLE
Downloaded a 3d skin for chems' website, but all the 3d aspects are red

### ISSUE THREAD

**Issue by searching-for-answers** [mikeoverbay/TankExporter#95]
Ok so i downlaoded the mountaneer skin for the UDES 03 from chems's website he put up to share his skins, i wanted some of them but i've never used tank exported so maybe i jsut did something wrong, but the rendered, jsut with all 3d aspects painted in a bright red, any clues on how i fix this?
![Screenshot (26)](https://github.com/mikeoverbay/TankExporter/assets/143447976/16be7a91-fe44-44c9-bacb-029a46394a30)

**Comment by searching-for-answers** [comment]
To put it clear he's the comparison of how it should be
![How it should be](https://github.com/mikeoverbay/TankExporter/assets/143447976/7dc6762e-6acd-4546-a34d-27775fafff86)

**Comment by searching-for-answers** [comment]
I've just tried in game and it's so goofy
![Screenshot (28)](https://github.com/mikeoverbay/TankExporter/assets/143447976/042ac0be-9c21-4187-a814-066e79ada933)

**Comment by Sparton385** [comment]
So the red textures means the xml files either arent pulling the right textures, or the textures for the 3d skin aren't in actual mod file

**Comment by searching-for-answers** [comment]
they are fbx files, anything to do with that or any guesses on how to solve this? but thanks for addressing it

**Comment by mikeoverbay** [comment]
Give me a link to these mods and I'll have a look.

**Comment by mikeoverbay** [comment]
OK...
Grab the 3D and open it. the WOTMOD file.
In side you will see a vehiches folder. Drag and drop that in the the res_mods in the current game version folder.
This is the folder on my machine : C:\Games\World_of_Tanks_NA\res_mods\1.21.1.1
Run the game and see if it shows the skins correctly.

TE will load the tank if its found in the res_mods path.
This is what I loaded into TE after dragging vehicles to the res_mods folder.


![S21_UDES_03](https://github.com/mikeoverbay/TankExporter/assets/15058778/14c2071c-77e3-4332-97a0-85d430719f2e)

Let me know if this works.

**Comment by mikeoverbay** [comment]
The reason this works is because there are skin paths in the visual file that are not in the normal model.
Also there is a folder with custom textures. With out these, WOT is going to show red because it can't find the textures.

**Comment by mikeoverbay** [comment]
Seems ok.
![shot_005](https://github.com/mikeoverbay/TankExporter/assets/15058778/f1152707-817d-4773-8f70-2fc64be44d82)

**Comment by searching-for-answers** [comment]
I love you man (no homo, or eys if you want i don't know your preferences).
![Screenshot (31)](https://github.com/mikeoverbay/TankExporter/assets/143447976/48f7cddd-4f19-446a-99be-0240789f4a72)
