### ISSUE TITLE
Skinned gun ?

### ISSUE THREAD

**Issue by brokeDude2901** [mikeoverbay/TankExporter#99]
Is it possible to remodel the gun that doesn't break the gun animation (skinned) ? 

It seems there is no way to tell the exporter to know which part is static (mantlet) and which part is skinned (gun barrel)

**Comment by mikeoverbay** [comment]
vertex colors control what part of the gun moves and doesn't.
vertices that recoil will have a value of 3, 3, 3
Non recoil parts will have a vertex color value of 0, 3 ,0
Click the vertex color button on the far right, its the colored cube,
Click the texture button, 2nd from bottom far right,
Select the gun textures and pic the left color texture.
In that window, click 'Show UVs'
Now when you mouse over the guns mesh, it will show what the vertex colors are as the index values in the main window, upper left.
Hope this helps.

**Comment by mikeoverbay** [comment]
![image](https://github.com/user-attachments/assets/3c394f3e-2305-4192-9754-a035a798a016)
